bench/README.md, cmd/operator/deploy/operator/operator.yaml, cmd/operator/deploy/rule-evaluator/deployment.yaml, examples/frontend.yaml, examples/operator.yaml, pkg/operator/operator.go
I also rearranged the yaml so from top-to-bottom the resources are created in order of dependency.
=> Updated example to include public images

pkg/operator/e2e/main_test.go
These tests ensure:
- The generated rule-evaluator config is what's expected from a test CRD.
- User-provided `alertmanager_config` is read in properly.
- Dummy TLS secrets are created in the gmp-system namespace for use by the managed rule-evaluator.
=> Add e2e tests for managed rule-evaluator and CRD

pkg/operator/collection.go
=> Remove honoring hardcoded scrape configmaps

pkg/operator/apis/monitoring/v1alpha1/types.go
If a port number is not specified on the Pod resource our previous
filtering mechanism didn't generate a target.
However, we can safely produce targets in this scenario in any case
as we generate a scrape config per specified endpoint and can simply
hardcode all target candidates to the given port number.
This turned out much easier than expected.
=> Scrape port numbers even if not specified on Pod

cmd/operator/deploy/operator/05-deployment.yaml, examples/operator.yaml, pkg/operator/collection.go, pkg/operator/operator.go, pkg/operator/operator_config.go
Also amend sample yaml file, move selector label to metadata label.
=> per gke's suggestion, use dash instead of under.

pkg/operator/collection.go, pkg/operator/operator_config.go
* Revert to using the label selectors defined in v0.1.1.
* Add comment to never modify them.
=> Use fixed label selectors

pkg/export/transform.go, pkg/operator/e2e/main_test.go
Verified with `make presubmit`
=> alertmanager endpoints test fix

doc/api.md, hack/Dockerfile
=> use pod-docgen v0.53.1

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, cmd/rule-evaluator/main.go, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go, pkg/operator/operator.go
* e2e tests completed successfully
* manually verified upgrade from v0.1.1 to v0.2.0
=> Cut v0.2.0

cmd/operator/main.go
This reverts commit 774d956b7e785f74a27ff185248f032e7ac0c476.
=> Revert "Change default for --host-network to false"

pkg/export/transform.go, pkg/export/transform_test.go
* Handle potential NaN values in histogram series
* Mitigate some consequences of race conditions in instrumentation
libraries when producing /metrics output
=> Handle NaN histogram series, mitigate race conditions

Makefile, pkg/export/setup/setup.go
Fixes GoogleCloudPlatform/prometheus-engine#158
=> Fix make test

cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml, cmd/operator/deploy/crds/monitoring.googleapis.com_podmonitorings.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, doc/api.md, examples/example-app.yaml, examples/frontend.yaml, examples/grafana.yaml, hack/presubmit.sh, manifests/rule-evaluator.yaml, manifests/setup.yaml, pkg/operator/apis/monitoring/v1alpha1/types.go, pkg/operator/collection.go, pkg/operator/operator_config.go, pkg/operator/operator_test.go
* Cleaned up some bad merge conflicts.
* Got `make ps` running. kindtest target still needs to be fixed.
* Add linux and amd64 node selectors for managed collection and example
manifests.
=> Fix presubmit.sh and add node selectors

cmd/operator/main.go, pkg/operator/collection.go, pkg/operator/operator.go, pkg/operator/operator_config.go
customer could pass a ua information to operator, and operator will propagate ua information to collector and evaluator.
=> add flag to add ua information

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go, pkg/operator/collection.go, pkg/operator/e2e/main_test.go, pkg/operator/operator.go, pkg/operator/operator_config.go
Bump once the two outstanding PRs are merged.
=> Bump version to v0.4.0

pkg/operator/collection.go
Hello Guys, thanks for this amazing project.
I want to fix a bug we discovered yesterday and is preventing us from collecting some metrics.
I would like to contribute with a documentation on the Collector options as well but I'll do it in another PR.
=> [Fix] Issue #235 related to Collector not readind opts

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go, pkg/operator/collection.go, pkg/operator/e2e/main_test.go, pkg/operator/operator.go, pkg/operator/operator_config.go
- Update used images
- Update Prometheus to 2.35 canonical image
- Remove config stripping
- make presubmit
=> Cut v0.4.2

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/operator/operator.go
Images actually published with a bumped tag. Reflect that in our official manifests.
=> Cut v0.4.2-gke.1

cmd/frontend/README.md, cmd/frontend/main.go
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/242
=> Add basic auth to frontend handler

cmd/operator/README.md
Edit: after help from @damemi , I realized the original error I was trying to fix was caused by the instructions for running the operator locally being incorrect. This PR fixes that.
=> Fix instructions for running operator locally

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
Changing the image versions to correspond with our upcoming release
=> Bump gmp images to v0.5.0

examples/prometheus.yaml
Mimics our [collector](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/f753d7786f64c12be9b8c4408f2ab2c67705423f/cmd/operator/deploy/operator/10-collector.yaml#L31-L33) annotations for the Prometheus example.
=> add safe eviction annotation

hack/presubmit.sh
This is already included in the hack [`Dockerfile`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/hack/Dockerfile#L5-L8).
=> no need to install po-docgen as it is part of the Dockerfile

cmd/frontend/main.go
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/374
=> Fixing confusing error message

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
Bump the export library version in code as well as the anticipated manifest image versions.
=> prepare v0.6.0 cut

examples/hpa/README.md
Sync the instructions from the latest HPA public doc: https://cloud.google.com/stackdriver/docs/managed-prometheus/hpa
cc.@courageJ
=> [Enhance] Update HPA README

examples/hpa/README.md, examples/hpa/cm.yaml
Use a more recent version of prometheus-adapter.
=> use newer prometheus-adapter manifests

examples/couchdb/exporter.yaml.snippet
=> Update couchdb sample snippet

pkg/operator/target_status.go
…if no PodMonitorings or ClusterPodMonitorings are provided
=> Short circuit target polling

pkg/export/setup/setup.go
=> Add Anthos hybrid distributions to UserAgentMode

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml
Specify the workload requests of CPU/RAM to reflect what they use at idle.
=> Use lower requests

cmd/config-reloader/Dockerfile, cmd/frontend/Dockerfile, cmd/operator/Dockerfile, cmd/rule-evaluator/Dockerfile, hack/Dockerfile, pkg/operator/generated/clientset/versioned/fake/register.go, pkg/operator/generated/clientset/versioned/scheme/register.go
=> Build with Golang 1.20 for release 0.5

Makefile, cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
Done that via Makefile:
`make updateversions`
=> Bumped examples and manifest versions to latest.

cmd/operator/main.go, cmd/rule-evaluator/main.go
This is an issue we observed on a single internal cluster. This logging would help us debug why this happened.
=> Log an error when unable to fetch Google Cloud metadata

Makefile, cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
Prepare for `v0.7.0` tag by bumping manifest images.
=> bump images for tag

hack/presubmit.sh
Missed updating this version in #494.
=> Update controller-gen in presubmit script

pkg/operator/generated/clientset/versioned/clientset.go, pkg/operator/generated/informers/externalversions/factory.go
Update clientset and factory generated files for changes introduced by upgrading `controller-gen`.
=> Update generated files with controller-gen v0.12.0

pkg/export/export.go
Note: unit tests will fail without the tag.
=> Prepare for 0.7.2-rc.0 tag

examples/consul/exporter.yaml.snippet
* [updated the image in the example to reflect the latest version of consul](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/94545649be6d28030f4ba07ce93ceafd6e92d062)
For consistency, where the test results for currency tell us:
* The dashboards/alerts are backwards compatible with new version of the application and the exporter
We are opting to keep the `minimum_supported_version` as it is, while the example in the documentation will reflect the latest version of the app/exporter.
=> Updated Consul exporter yaml snippet

.github/workflows/auto-assign-pr.yml
https://github.com/pozil/auto-assign-issue/pull/115 was merged.
=> auto-assign: Moved to upstream GH action after merge.

examples/instrumentation/go-synthetic/go-synthetic.yaml
max-count arg was removed by PR #539
=> also rm max-count frm go-synthetic.yaml

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/alertmanager.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml
Lower resource requests to match idle usage
=> Lower resource requests to idle usage

Makefile, e2e/alertmanager_test.go, e2e/collector_test.go, e2e/operator_context_test.go, e2e/ruler_test.go
My original take on this is in #413 but they potentially discovered real bugs so I split out the e2e ones and ran the latest linter.
=> Fix lint warnings in e2e package

examples/shared-configs/README.md, examples/shared-configs/common.yaml, examples/shared-configs/kustomization.yaml, examples/shared-configs/podmonitorings.yaml
Add an example that shows you how to setup a common configuration and apply it across or `PodMonitoring`.
=> Shared TLS configuration example

Makefile, cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/instrumentation/go-synthetic/go-synthetic.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml
=> Update 0.8.0 images

e2e/collector_test.go, e2e/kubeutil/deployment.go, e2e/kubeutil/parse.go, e2e/kubeutil/pod.go, e2e/network.go, e2e/operator_context_test.go, e2e/syntheticutil.go, pkg/operator/operator.go
Prereq before merge: #641
This change opens up a variety of other tests, e.g. authorization tests.
=> Add synthetic example app e2e test

pkg/operator/operator.go
In preparation for removing permissions from GKE environments, add an explicit check to ensure updating CA Bundle on webhooks is allowed before blindly attempting to do so forever.
=> fix: check for permissions before updating webhooks

hack/presubmit.sh
This reverts commit 7ca3c5c4e2a43cad2e79edbf724bc58cf064e423.
=> Revert "chore: switch to kube-codegen"

Makefile, cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, examples/frontend.yaml, examples/instrumentation/go-synthetic/go-synthetic.yaml, examples/prometheus.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
After this PR, we will update the export version and then create the tag.
=> Prepare 0.8.2 release

Makefile
Intention is to skip not fail those. There was bug with IF makefile statement.
=> Fixed gcm based tests failures for external contributors.

e2e/authorization_test.go, e2e/webhook_test.go
This PR adds a placeholder for the OAuth2 e2e test.
=> Add basic OAuth 2 e2e test

.github/workflows/presubmit.yml, e2e/kubeutil/daemonset.go, e2e/kubeutil/deployment.go, e2e/kubeutil/pod.go, e2e/kubeutil/resource.go, e2e/operator_context_test.go, e2e/operatorutil/operatorutil.go, e2e/operatorutil/podmonitoringutil.go, e2e/webhook_test.go
See individual commits for details.
Example flakiness: https://github.com/GoogleCloudPlatform/prometheus-engine/actions/runs/7292958602/job/19875027487?pr=652
=> Further e2e test flakiness improvements

examples/instrumentation/go-synthetic/auth.go
Prometheus uses POST requests so this is a prerequisite for writing e2e tests that utilize the example application.
=> Fix example-app OAuth2 should support POST requests

Makefile, cmd/datasource-syncer/datasource-syncer.yaml
Also updated Makefile to automatically update datasource-syncer's image tag to the latest.
=> Update datasource-syncer image address

e2e/collector_test.go, e2e/operatorutil/commonmonitoringutil.go, e2e/operatorutil/nodemonitoringutil.go, e2e/operatorutil/podmonitoringutil.go, pkg/operator/apis/monitoring/v1/node_types.go, pkg/operator/apis/monitoring/v1/node_types_test.go
1. Added E2E support for NodeMonitoring
2. Modified instance relabeling in node_types.go
=> NodeMonitoring E2E test support

.golangci.yml, cmd/config-reloader/main.go, cmd/datasource-syncer/main.go, cmd/rule-evaluator/main.go, e2e/ruler_test.go, pkg/export/gce_token_source.go, pkg/export/setup/setup.go, pkg/operator/apis/monitoring/v1/pod_types.go, pkg/operator/collection.go, pkg/operator/operator.go, pkg/operator/operator_config.go, pkg/operator/rules.go
Add linter to check fields have matching name and value for loggers.
=> style: add additional linters

cmd/datasource-syncer/README.md
1. Update cronjob command with namespace
2. Correct local Grafana address
=> docs: improve datasource-syncer README

cmd/operator/deploy/crds/monitoring.googleapis.com_nodemonitorings.yaml, manifests/setup.yaml, pkg/operator/apis/monitoring/v1/node_types.go
NodeMonitoring is cluster-scoped.
=> fix: make NodeMonitoring cluster-scoped

Makefile, cmd/datasource-syncer/datasource-syncer.yaml
Also updated Makefile to reflect latest version.
=> chore: update datasource-syncer to latest release

.github/workflows/release-please.yml
=> ci: add release-please

Makefile
Primarily to get faster local runs!
=> refactor: add command that runs e2e tests without rebuilding images

charts/operator/templates/deployment.yaml, manifests/operator.yaml
Remove duplicate labels on operator.
=> chore: correct labels

cmd/frontend/main.go
Whenever a user cancels a request to GCM via front end they see the error messages `requesting GCM failed` and `context canceled`. These error messages are unclear and it makes it seem like GCM or frontend failed. Users usually see this error because the program they are using to call frontend has a timeout. 
https://github.com/GoogleCloudPlatform/prometheus-engine/assets/89922129/3485cee1-ec0d-4c54-baf8-2f70b6b48702
We have received four support tickets about this error message. This change returns a more direct and actionable error message.
=> chore: specify when frontend returns an error due to user cancelation

e2e/webhook_test.go
Restart deployment instead of deleting pods in webhook e2e test.
=> refactor: restart deployment

cmd/config-reloader/Dockerfile, cmd/datasource-syncer/Dockerfile, cmd/frontend/Dockerfile, cmd/operator/Dockerfile, cmd/rule-evaluator/Dockerfile, examples/instrumentation/go-synthetic/Dockerfile
Enable boringcrypto flag for Go builds.
=> chore: enable boringcrypto

cmd/rule-evaluator/main.go, e2e/deploy/deploy.go
Adds a new flag to the rule-evaluator `--query.debug.disable-auth` which mirrors `--export.debug.disable-auth` but for querying rather than writing.
This flag is then enabled on e2e tests which lets the rule-evaluator start without requiring credentials.
Previously, we hacked this by creating a default credentials file, but this was removed in https://github.com/GoogleCloudPlatform/prometheus-engine/pull/813
=> fix(e2e): start rule-evaluator without auth in e2e tests

Makefile, e2e/deploy/operator.go, e2e/kube/deployment.go, e2e/kube/pod.go, e2e/main_test.go, e2e/webhook_test.go, pkg/export/export.go, pkg/operator/operator.go
Ran a `git rebase -i v0.11.0-rc.3` to sync this guy up.
=> Bring release branch up to date with v0.11.0-rc.3 tag on main

charts/operator/crds/monitoring.googleapis.com_operatorconfigs.yaml, doc/api.md, e2e/alertmanager_test.go, e2e/ruler_test.go, manifests/setup.yaml, pkg/operator/apis/monitoring/v1/operator_types.go, pkg/operator/collection.go, pkg/operator/collection_test.go, pkg/operator/rules.go
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/549
Reopened https://github.com/GoogleCloudPlatform/prometheus-engine/pull/763
Depends on:
=> feat: apply OperatorConfig compression setting for rule-eval. configMap from *Rules CRs

pkg/operator/collection.go, pkg/operator/operator_config.go
Title should be self-explanatory - small change I found useful, but don't want to bloat other PRs with this.
=> refactor(operator): improve extra args injection readability

pkg/operator/operator_config.go
Makes secrets more consistent with ConfigMap (which supports both string and binary formats), as well as with other selectors (e.g. HTTPClientConfig) which already supports this.
=> fix(operator): support StringData for secret selectors

.golangci.yml, pkg/export/bench/app/example_app.go, pkg/export/gcm/export_gcm_test.go, pkg/secrets/manager.go
promlinter: `Check Prometheus metrics naming via promlint.`
=> style: enable promlinter

cmd/config-reloader/main.go
This should fix misleading restart of config-reloader which happeend in the past, yet giving us some extra guarantee when readiness url is misconfigured.
Alternative is to again - [remove startup check logic](https://github.com/GoogleCloudPlatform/prometheus-engine/pull/526) and ensure our tests guards against misconfiguration of url in our manifests (or metric/alert on configuration not reloading, but's harder). Since the team was not comfortable with removal of readiness check, let's try something that will help in common case or config-reloader starting faster.
=> feat: Made config-reloader resilient to initial readiness server unavailability (5s default timeout).

e2e/alertmanager_test.go, e2e/authorization_test.go, e2e/collector_test.go, e2e/deploy/operator.go, e2e/kube/debug.go, e2e/kube/pod.go, e2e/main_test.go, e2e/ruler_test.go, e2e/webhook_test.go
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/808
Part 2 of https://github.com/GoogleCloudPlatform/prometheus-engine/pull/950
=> refactor: remove all clientset usage on e2e tests

cmd/operator/deploy/operator/05-deployment.yaml, cmd/operator/deploy/operator/10-collector.yaml, cmd/operator/deploy/operator/11-rule-evaluator.yaml, cmd/operator/deploy/operator/12-alertmanager.yaml, cmd/operator/deploy/rule-evaluator/01-deployment.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml
Update final GKE images in manifest to prepare release tag
=> Prepare 0.10.0 release

pkg/operator/operator.go
=> fix: remove unused import

examples/vpa-rules.yaml
Add an example VerticalPodAutoscaler for the rule-evaluator.
=> chore: create rule-evaluator example vpa

charts/operator/crds/monitoring.googleapis.com_clusterrules.yaml, charts/operator/crds/monitoring.googleapis.com_globalrules.yaml, charts/operator/crds/monitoring.googleapis.com_rules.yaml, doc/api.md, manifests/setup.yaml, pkg/operator/apis/monitoring/v1/monitoring_types.go, pkg/operator/apis/monitoring/v1/pod_types.go, pkg/operator/apis/monitoring/v1/pod_types_test.go, pkg/operator/apis/monitoring/v1/rules_types.go, pkg/operator/collection.go, pkg/operator/collection_test.go, pkg/operator/rules.go, pkg/operator/rules_test.go
Add MonitoringStatus to all Rules CRDs.
=> feat: populate rules status

pkg/operator/collection.go
Remove `cmon := cm` and `pmon := pm`  since it was [removed from the ClusterNodeMonitoring loop.](https://github.com/GoogleCloudPlatform/prometheus-engine/pull/994/files/0d72f83444dace0273227bf52c6a1aa2a70cc45a#r1625153509)
=> chore: make functions consistent

e2e/authorization_test.go, pkg/operator/apis/monitoring/v1/http_types.go, pkg/operator/apis/monitoring/v1/http_types_test.go
Adds:
- https://github.com/GoogleCloudPlatform/prometheus-engine/pull/995
- https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1006
=> Patch secrets management fix for 0.12

e2e/authorization_test.go, pkg/operator/apis/monitoring/v1/http_types.go, pkg/operator/apis/monitoring/v1/http_types_test.go
Adds:
- https://github.com/GoogleCloudPlatform/prometheus-engine/pull/995
- https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1006
=> Patch secrets management fix for 0.13

examples/kube-state-metrics/kube-state-metrics.yaml
Tested on cluster delete-me-ksm-test in lees-gmp
=> fix: Update kube-state-metrics.yaml to 2.12.0

pkg/export/setup/setup_test.go
Turns out @TheSpiritXIII [suggestion](https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1021#discussion_r1635448295) was worth doing 🙃
=> fix: make sure tests are not failing on cloudtop

charts/operator/templates/collector.yaml, charts/operator/values.yaml, manifests/operator.yaml
Cherry pick (and simplify) https://github.com/GoogleCloudPlatform/prometheus-engine/pull/947 to resolve common WAL issues.
=> fix: added delete data flag for fix WAL issues

cmd/frontend/Dockerfile, examples/instrumentation/go-synthetic/Dockerfile
Based on https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1040
=> chore: security patch Golang for the example app

cmd/rule-evaluator/README.md, cmd/rule-evaluator/main.go
See description of original PR: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1001
=> refactor: cleanup rule-evaluator flags

examples/node-exporter/node-exporter.yaml
fix: update node-exporter.yaml to 1.8.2
=> fix: update node-exporter.yaml to 1.8.2

charts/values.global.yaml, cmd/datasource-syncer/datasource-syncer.yaml, examples/collector-max-throughput.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml
Update images on main in sync with v0.12.0.
=> chore: update images

cmd/rule-evaluator/main.go, pkg/export/setup/setup.go
Makes it easier for clients to use the setup code.
=> refactor: add setup opts utility

cmd/rule-evaluator/main.go, pkg/operator/operator_config.go, pkg/operator/operator_config_test.go
This is the rule-evaluator equivalent of https://github.com/GoogleCloudPlatform/prometheus/pull/180
The following are now settable in the rule-evaluator Prometheus config:
```yaml
google_cloud:
export:
match: []string
compression: string
credentials: string
```
When both CLI arguments and configurations are present, the CLI arguments will be the default and the set configurations will override the CLI arguments.
=> feat: allow loading rule-evaluator export options from config

cmd/rule-evaluator/main.go
Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1059
=> feat: hot-reloader rule-evaluator query options from config

charts/operator/templates/role.yaml, manifests/operator.yaml, pkg/operator/collection.go
Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1003
=> refactor: remove DaemonSet update and patch permission

charts/operator/templates/role.yaml, manifests/operator.yaml, pkg/operator/operator_config.go
Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1074
=> refactor: remove StatefulSet update and patch permission

charts/operator/templates/role.yaml, manifests/operator.yaml, pkg/operator/operator_config.go
Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1105
=> refactor: remove Deployment update and patch permission

charts/operator/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml, charts/operator/crds/monitoring.googleapis.com_podmonitorings.yaml, doc/api.md, manifests/setup.yaml, pkg/operator/apis/monitoring/v1/pod_config.go, pkg/operator/apis/monitoring/v1/pod_config_test.go, pkg/operator/apis/monitoring/v1/pod_types.go, pkg/operator/collection_test.go
This reverts commit cb350d3c0b7e12ef92c4962b344506b949e87699.
Ref https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1065
=> Revert "feat: workload labels"

examples/instrumentation/go-synthetic/go-synthetic.yaml, examples/prometheus.yaml
=> fix: use latest image tags in manifests

examples/prometheus.yaml
=> chore: bump prometheus example images

charts/values.global.yaml
=> bump images on release 0.15

pkg/export/transform.go, pkg/export/transform_test.go
Such error will produce debug logs with mention of the series labels, instead of error log for GCM write (with no mention of series labels). In separate PRs I plan to:
* challenge debug level for those errors (should it be error/warn?)
* add runtime log level feature https://github.com/prometheus/prometheus/issues/10352#issuecomment-2621663426
* print series that are in the failed send batch in error log.
Helps debugging b/387200417
Signed-off-by: bwplotka <bwplotka@google.com>
=> feat: reject problematic histograms early

cmd/rule-evaluator/Dockerfile, hack/Dockerfile
Fix & testing https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1343
=> fix: rule-eval docker build for 0.14

examples/tf-serving/README.md, examples/tf-serving/exporter.yaml.snippet, examples/tf-serving/monitoring_config.txt, examples/tf-serving/pod-monitoring.yaml, examples/torchserve/README.md, examples/torchserve/config.properties.snippet, examples/torchserve/exporter.yaml.snippet, examples/torchserve/pod-monitoring.yaml
Convention from past docs we are hewing to here:
- if the file is a valid yaml, it ends with .yaml
- if the file is a diff with '+' to illustrate how you should be modifying your existing setup, it ends with .snippet so users don't blindly apply it.
=> docs: add Tensorflow Serving and TorchServe sample yamls

pkg/operator/operator_config.go, pkg/operator/operator_config_test.go
Fix: https://github.com/GoogleCloudPlatform/prometheus-engine/issues/1550
Alternative to https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1558#pullrequestreview-2726442790
=> fix: re-encode without obfuscation for AM config

pkg/operator/operator_config.go, pkg/operator/operator_config_test.go
Forward porting of https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1559 to fix https://github.com/GoogleCloudPlatform/prometheus-engine/issues/1550
=> fix: re-encode without obfuscation for AM config (0.15 bugfix port)

pkg/operator/operator_config.go, pkg/operator/operator_config_test.go
Forward porting of https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1559 to fix https://github.com/GoogleCloudPlatform/prometheus-engine/issues/1550
=> fix: re-encode without obfuscation for AM config (0.16 bugfix port).

charts/values.global.yaml, cmd/datasource-syncer/datasource-syncer.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
This PR prepares the release candidate v0.14.3-rc.0
=> chore: prepare for 0.14.3-rc.0 release

charts/values.global.yaml, cmd/datasource-syncer/datasource-syncer.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
This PR prepares the release candidate v0.15.3-rc.0
=> chore: prepare for 0.15.3-rc.0 release

charts/values.global.yaml, cmd/datasource-syncer/datasource-syncer.yaml, manifests/operator.yaml, manifests/rule-evaluator.yaml, pkg/export/export.go
This PR prepares the release candidate v0.16.1-rc.0
=> chore: prepare for 0.16.1-rc.0 release

pkg/operator/operator_config.go, pkg/operator/operator_config_test.go
Forward porting of https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1559 to fix https://github.com/GoogleCloudPlatform/prometheus-engine/issues/1550
=> fix: re-encode without obfuscation for AM config (main bugport).
