- examples/example-app.yaml
- examples/prometheus.yaml
Add Kubernetes manifests to manually deploy a Prometheus server
and an example application. The Prometheus server is configured to
scrape the example app.
> Add Prometheus and example app manifets

- pkg/export/transform.go
This map slips through escape analysis and is actually allocated each time for no good reason.
This reduces allocated bytes/sec by about 25%, which is very significant. However, CPU and memory usage seem not affected really, which is very surprising as that correlates very directly usually. Makes me think this just counts towards the alloc metric but doesn't actually allocate new memory each time – not sure if that's a thing.
Anyway, at least this will remove noise from profiling for future improvements.
> Avoid allocations in metadata retrieval func

- pkg/operator/operator.go
- pkg/operator/webhook.go
- pkg/operator/webhook_test.go
The flag was not used previously. This made the webhook server default
to 9443 while the unset port field in the ValidatingWebhookConfiguration
defaults to 443. Hence the webhooks were never active.
This is a good thing to test once we've a suite that runs the operator in a cluster.
> Correctly use webhook listen address

- cmd/operator/main.go
You had this originally and I asked you to change it.
When testing I realized now though that this will just cause unnecessary confusion so reverting to how you did it initially.
> Use gmp-public as default public namespace

- pkg/export/export.go
- pkg/export/series_cache.go
- pkg/export/transform.go
- pkg/export/transform_test.go
The exposition format allows for series for a single histogram to not be
grouped together. It only requires all histograms for a metric name to
be grouped together and the buckets for a single histogram to be in
ascending order within that group.
While processing a batch we build a cache for each histogram and produce
a GCM distribution once we've observed sum, count, and infinity bucket
series.
Benchmarking the change within a Prometheus server shows no noticeable change in CPU or memory consumption.
> Support ungrouped histograms

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/main.go
- examples/operator.yaml
- pkg/operator/e2e/context.go
- pkg/operator/operator.go
Webhooks with self-signed certs will not be accepted by the kubernetes API server.
> Removing cert self-sign option from operator

- pkg/operator/apis/monitoring/v1alpha1/types.go
- pkg/operator/apis/monitoring/v1alpha1/types_test.go
Setting it to the empty string actually defines a valid URL that then
fails to proxy through at scrape time. Thus we must make sure that
the parameter is truly unset in the generated config.
> Don't set empty proxy URL

- pkg/operator/apis/monitoring/v1alpha1/types.go
- pkg/operator/apis/monitoring/v1alpha1/types_test.go
Mirrored changes from PodMonitoring. Verified with `make presubmit`.
> Do not use empty proxy url for clusterpodmonitoring

- cmd/operator/main.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
1. Added flags to pass-in certificate payload to the operator.
2. Added function ensureCerts that will handle the cert/key uses.
> Add webhook TLS cert flags

- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/deploy/operator/04-rolebinding.yaml
- manifests/operator.yaml
- pkg/operator/operator.go
- pkg/operator/rules.go
- pkg/rules/rules.go
Validate the various rules resources including running the upstream
validation logic on the generated result. While this doesn't yield the
best error messages, it gives the best guarantee that the result can
be picked up by the rule-evaluator.
> Validate rules resources

- cmd/operator/main.go
- pkg/export/setup/setup.go
- pkg/operator/e2e/main_test.go
- pkg/operator/rules.go
We previously incorrectly assumed we could label data in regional
cluster by the zone of the machine it originated from. That may
cause theoretical collisions however and we must always set location
to the cluster's official location.
This in practice makes our lives easier as we can simply enforce the
location label of all rule data to match the cluster location.
> Handle cluster location correctly

- Makefile
- hack/Dockerfile
- hack/kind-config.yaml
- hack/kind-test.sh
Reverts GoogleCloudPlatform/prometheus-engine#120
This change made `make kindtest` and `make presubmit` start failing the collector test for me. The collector crashloops as it cannot find default credentials and doesn't get explicit ones either.
This is different from the case for which our tests have the `--skip-gcm` flag, where it has credentails, but they lack permissions.
I'm not entirely sure what the reason is and how it relates to this change. But undoing first so the tests work again.
> Revert "Fix "dockerception" and use sibling containers over child containers"

- pkg/export/bench/README.md
- pkg/export/bench/example_app.go
- pkg/export/bench/prometheus.yaml
- pkg/export/bench/run.sh
- pkg/export/bench/server.go
- pkg/export/transform.go
The histograms used slices for bounds and values in the proto that were
originally allocated for a memory-pooled intermediate struct. The struct
is returned to the pool before the proto is sent.
Thus the next histogram overwrites the slices concurrently. Allocating
unique slices for the proto solves the issue.
> Fix race condition in histogram building

- cmd/frontend/main.go
- pkg/ui/ui.go
Add the flag with semantics equivalent to upstream Prometheus to
correctly redirect when running behind a reverse proxy.
> Add --web.external-url flag

- manifests/setup.yaml
CRDs with a status section gets rejected by Anthos Config Sync,
let's remove it.
> Remove status from manifests/setup.yaml

- examples/prometheus.yaml
Update example to support heterogenous on prem clusters that may have windows/arm64 nodes.
> Explicit node type selector for windows/arm nodes

- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/deploy/operator/04-rolebinding.yaml
- manifests/operator.yaml
Split up read and write permissions so that write permissions move to a `Role` and are thus namespaced. Also constrain to the exact resource names that are written by the operator.
Read permissions remain in `ClusterRules` so the non-namespaced watches the controller-runtime library requires us to use keep working.
> Minimize permissions

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- examples/frontend.yaml
- examples/prometheus.yaml
- hack/presubmit.sh
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
- pkg/operator/collection.go
- pkg/operator/operator_config.go
* The motivation to make this explicitly true everywhere was the [terraform provider](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/workload-identity#inputs) for WI-enabled GKE clusters defaults `automountServiceToken=false`, which prevents images from reaching necessary GCP endpoints (i.e. monitoring API). As the pod spec `automountServiceAccountToken` field [takes precedence](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) over the service account's field, we set it everywhere we can to ensure access.
* Also automate deletion of extra CRD status field
> Specify automount of SA token everywhere.

- cmd/operator/deploy/operator/10-collector.yaml
- pkg/operator/collection.go
Change to an approach where the collector DaemonSet is provided
externally within the operator installation bundle. The operator then
only updates runtime-dependent values into the DaemonSet.
This allows users to do advanced customization (node affinity, priority
class, etc.) without the need for configuration knobs through the
OperatorConfig or operator flags.
This approach would be extended to the rule evaluator deployment if accepted.
> [DRAFT] Create DaemonSet externally and inject config

- cmd/operator/deploy/operator/03-role.yaml
- manifests/operator.yaml
- pkg/operator/apis/monitoring/v1alpha1/types_test.go
- pkg/operator/collection.go
- pkg/operator/operator_config.go
I noticed that a from-scratch kubectl install from `main` was throwing a lot of permissions issues. For example:
```
"level":"error","ts":1650043097.3943744,"logger":"controller.rules","msg":"Reconciler error","reconciler group":"monitoring.googleapis.com","reconciler kind":"OperatorConfig","name":"config","namespace":"gmp-public","error":"ensure rule configmaps: create generated rules: configmaps is forbidden: User \"system:serviceaccount:gmp-system:operator\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"gmp-system\"","errorVerbose":"configmaps is forbidden: User \"system:serviceaccount:gmp-system:operator\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"gmp-system\"\ncreate generated …
```
> Fix RBAC by removing resourceNames

- cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
- cmd/operator/deploy/crds/monitoring.googleapis.com_podmonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1alpha1/types.go
- pkg/operator/apis/monitoring/v1alpha1/types_test.go
- pkg/operator/collection.go
- pkg/operator/e2e/context.go
- pkg/operator/e2e/main_test.go
- pkg/operator/operator_config.go
The fix of numeric port handling may make certain configurations that worked before no longer work.
This is a necessary part of the bug fix unfortunately and we'll need to mention it in the release notes.
> Refactor config generation, fix numeric port handling

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/operator/06-service.yaml
- cmd/operator/deploy/operator/08-validatingwebhookconfiguration.yaml
- cmd/operator/deploy/operator/09-mutatingwebhookconfiguration.yaml
- cmd/operator/main.go
- manifests/operator.yaml
This enables managed collection to work seamlessly on private GKE clusters with the [default firewall rules](https://cloud.google.com/kubernetes-engine/docs/concepts/firewall-rules#cluster-fws).
Note: for users upgrading using `kubectl` manually, a few attempts may be necessary as the operator is redeployed and the web server becomes available.
> Use port 10250 for admission webhooks

- cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
- cmd/operator/deploy/crds/monitoring.googleapis.com_podmonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/apis/monitoring/v1/types_test.go
When a scrape port is specified by number no longer generate a container
label to rely on Prmetheus' target deduplication behavior to ensure the
port is scraped exactly once whether it is declared in the Pod or not.
> Fix numerical port behavior

- cmd/operator/deploy/operator/06-service.yaml
- cmd/operator/deploy/operator/08-validatingwebhookconfiguration.yaml
- cmd/operator/deploy/operator/09-mutatingwebhookconfiguration.yaml
- manifests/operator.yaml
- pkg/operator/e2e/context.go
This is more to follow convention. This is typical of workloads running on GKE clusters.
> Use port 443 for webhook (operator) service

- cmd/operator/main.go
- pkg/operator/collection.go
- pkg/operator/e2e/context.go
- pkg/operator/operator.go
- pkg/operator/operator_config.go
For clusters that enforce resource limits on workloads. Tested manually and saw the limits set on the collectors and rule-evaluator.
> make CPU limits configurable

- examples/hpa/README.md
- examples/hpa/cm.yaml
- examples/hpa/example-app.yaml
- examples/hpa/hpa.yaml
- examples/hpa/pod-monitoring.yaml
Some example manifests for how to enable prometheus-adapter-powered HPA using GMP data.
> prometheus-adapter HPA example

- cmd/operator/deploy/operator/05-deployment.yaml
- manifests/operator.yaml
Following https://github.com/GoogleCloudPlatform/prometheus-engine/pull/179, set the matching `runAsNonRoot` security context on the operator pod
> Set runAsNonRoot on operator deployment spec

- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/main.go
- manifests/operator.yaml
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- vendor/github.com/go-logr/logr/testr/testr.go
- vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
The new `--cleanup-unless-annotation-key` flag will delete our previously operator-managed `collector` and `rule-evaluator` resources unless they have a particular annotation key.
> add annotation cleanup flag

- examples/node-exporter.yaml
gmp-system is supposed to be reserved (and will actually not be accessible on Autopilot); "monitoring" is also used by the kube-state-metrics manifest so we can do the same here.
> Change node-exporter to not use gmp-system ns

- .gitignore
- cmd/operator/README.md
- cmd/operator/deploy/crds/monitoring.googleapis.com_operatorconfigs.yaml
- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- doc/api.md
- manifests/operator.yaml
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/operator_config.go
This adds a manifest for a default AlertManager instance, as well as a boolean in the OperatorConfig to enable (or disable) wiring the rule-evaluator to point to this AlertManager.
> Deploy default AlertManager with operator

- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- manifests/operator.yaml
This fixes a bug where the collector and rule-evaluator pods start up before the config-reloader, causing the collector/evaluator to restart due to not being able to find a config. For example:
```
$ kubectl logs pod/rule-evaluator -n gmp-system -c evaluator
level=error ts=2022-07-25T19:14:05.872221429Z caller=main.go:144 msg="Error loading config (--config.file=/prometheus/config_out/config.yaml)" err="open /prometheus/config_out/config.yaml: no such file or directory"
```
this adds an init container to both pods that just creates the empty config file. in my testing, this appeared to fix the issue
> Initialize empty config for collector and evaluator pods

- examples/kube-state-metrics.yaml
- examples/node-exporter.yaml
1. Use `gmp-public` namespace instead of `monitoring` namespace
2. Add metricRelabeling rule to reflect filter recommendation in https://cloud.google.com/stackdriver/docs/managed-prometheus/cost-controls#filter-timeseries
> Update kube-state-metrics sample manifest

- examples/kube-state-metrics.yaml
- examples/node-exporter.yaml
-  version [2.3.0](https://github.com/kubernetes/kube-state-metrics/blob/e52d8ace1fae43248f225cd27a9bcc90296d6a01/README.md) has pretty good support from k8s1.19 to 1.23 
- Bump nodeexporter to 1.3.1 and minor deprecated flag change
> Bump kube-state-metrics to 2.3.0 and add missing labels

- cmd/frontend/main.go
Following https://github.com/GoogleCloudPlatform/prometheus-engine/pull/285
Return `401` for failed authentication
Return `403` for failed authorization
I think this will be better for debugging basic auth setups for users
> Use proper response codes for frontend auth

- cmd/operator/deploy/crds/monitoring.googleapis.com_operatorconfigs.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/types.go
Previous example filters basically filter out all metrics if applied verbatim
> Change example filters

- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/deploy/operator/04-rolebinding.yaml
- manifests/operator.yaml
- pkg/operator/collection.go
- pkg/operator/operator.go
- pkg/operator/operator_config.go
Constrains many of our ClusterRoles to a namespaced Role where possible (e.g. where we were already filtering by gmp-public or gmp-system). Further, this change updates the `controller-runtime` manager's watch-list to only watch those namespaces improving security and performance.
> Reduce ClusterRole

- pkg/e2e/fake_metric_server.go
- pkg/e2e/fake_metric_server_test.go
- pkg/export/export.go
This pull requests does the following:
- Adds `ListTimeSeries` to the `FakeMetricServer` that acts as a drop in replacement for the [endpoints listed here](https://cloud.google.com/monitoring/api/ref_v3/rpc#google.monitoring.v3.metricservice). 
- Adds unit tests to ensure the `FakeMetricServer`'s `ListTimeSeries` is behaving as expected.
- Stores points in the time series in the `FakeMetricServer` in decreasing timestamp order (the way we should return it in `ListTimeSeries`.
- Fixes the unit tests that changed as a result of the above.
- Fixes the `TestNil` test in `TestCreateTimeSeriesBadInput` -- it previously was not running.
- Fixes a bug in `CreateTimeSeries` where it did not properly add multiple time series and adds a test to test the scenario
This is the second of a few PRs that …
> Add ListTimeSeries to the FakeMetricServer

- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- examples/alertmanager.yaml
- examples/kube-state-metrics.yaml
- examples/node-exporter.yaml
- examples/prometheus.yaml
- manifests/operator.yaml
CPU is a throttled resource. Specifying a limit can result in premature throttling.
Also nothing prevents people from adding the limit themselves if they have that requirement.
> Remove cpu limits of our deployed resources.

- cmd/operator/deploy/operator/12-alertmanager.yaml
- manifests/operator.yaml
We forgot to put this in the v0.5.0 tag, but it's not a huge deal for those who kubectl apply these manifests.
> Use gcp alertmanager

- pkg/operator/e2e/context.go
To prevent NPEs when it's used
> Pass in Prometheus registry to e2e tests

- Makefile
- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- examples/example-app.yaml
- examples/frontend.yaml
- examples/grafana.yaml
- examples/kube-state-metrics.yaml
- examples/node-exporter.yaml
- examples/prometheus.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
1. Updated Makefile to use buildx for arm64 support
2. Updated operator.yaml to support arm64 
- Changed gke.gcr.io/gke-distroless/bash to gke.gcr.io/gke-distroless/bash:20220419 for arm64 support 
- Updated nodeSelector to nodeAffinity
> Configure Makefile to use buildx for arm64

- cmd/operator/deploy/operator/03-role.yaml
- manifests/operator.yaml
- pkg/operator/operator.go
No `StatefulSet`s are used:
```
$ grep -r StatefulSet pkg/
pkg/operator/e2e/context.go:            case *appsv1.StatefulSet:
pkg/operator/e2e/context.go:                    alertmanager := obj.(*appsv1.StatefulSet)
pkg/operator/e2e/context.go:                    if _, err := tctx.kubeClient.AppsV1().StatefulSets(tctx.namespace).Create(ctx, alertmanager, metav1.CreateOptions{}); err != nil {
pkg/operator/e2e/main_test.go:                  ss, err := t.kubeClient.AppsV1().StatefulSets(t.namespace).Get(ctx, operator.NameAlertmanager, metav1.GetOptions{})
pkg/operator/e2e/main_test.go:                          t.Log(errors.Errorf("getting alertmanager StatefulSet failed: %s", err))
pkg/operator/e2e/main_test.go:                          return false, errors.Errorf("getting alertmanager …
```
> Remove unused RBAC permissions

- examples/gke-control-plane/README.md
- examples/istio/README.md
- examples/istio/pod-monitoring.yaml
- examples/istio/rules.yaml
- examples/kube-state-metrics/README.md
- examples/kube-state-metrics/kube-state-metrics.yaml
- examples/kube-state-metrics/rules.yaml
- examples/kubelet-cadvisor/README.md
- examples/nginx/README.md
- examples/nginx/exporter.yaml.snippet
- examples/nginx/pod-monitoring.yaml
- examples/nginx/rules.yaml
- examples/node-exporter/README.md
- examples/node-exporter/node-exporter.yaml
- examples/node-exporter/rules.yaml
- examples/redis/README.md
- examples/redis/exporter.yaml.snippet
- examples/redis/pod-monitoring.yaml
- examples/redis/rules.yaml
- one subdirectory for every exporter we have documentation for
- add recommended rules when applicable
- use `.yaml.snippet` extension when snippet shows the recommended delta and cannot be applied as-is as standalone yaml
- add minimal README for each subdirectory pointing readers to the docs pages
> Reorganize examples directory

- Makefile
- build.yaml
- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- manifests/operator.yaml
This was running too slow locally and is usually not needed during normal iteration.
Move the multi-arch images to cloudbuild.
Also add some doc nits in the manifests.
> Use cloudbuild for multi-arch images

- pkg/export/transform.go
- pkg/export/transform_test.go
This PR is aimed to fix handling histograms with buckets out of the order. Prometheus does not guarantee buckets order. When `+Inf` bucket is not the last bucket we are not able to build distribution because `hasInfBucket` property will be overwritten. The following example cannot be parsed:
```
custom_query_time_bucket{role="coordinator",server="crdn-vc7b48n9",shortname="Coordinator0084",le="+Inf"} 35
custom_query_time_bucket{role="coordinator",server="crdn-vc7b48n9",shortname="Coordinator0084",le="1000"} 22
custom_query_time_bucket{role="coordinator",server="crdn-vc7b48n9",shortname="Coordinator0084",le="125"} 18
custom_query_time_bucket{role="coordinator",server="crdn-vc7b48n9",shortname="Coordinator0084",le="16"} 17
custom_query_time_bucket{role="coordinator",server="crdn-vc7b48n9",sho …
```
> Handle histogram with out-of-order buckets

- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/apis/monitoring/v1/types_test.go
Allow Prometheus to default to `replace` when `RelabelingRule.Action` is unspecified, as per the [docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config).
> Fix action defaulting

- pkg/operator/endpoint_status_builder.go
- pkg/operator/target_status.go
- pkg/operator/target_status_test.go
kubelet scrapePools are hardcoded by the operator and don't use a PodMonitoring/ClusterPodMonitoring. We want to be able to handle these without erroring.
- The expanding function in target_status_test.go was a little buggy, so I fixed that.
- Some light renaming and refactoring.
> Target status reporting - fix kubelet handling and unit test

- pkg/export/export.go
- pkg/export/shard.go
`samplesExported` is a little confusing - especially with [`samplesSent`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/d268d39aeb5ecdf1277b533b8640a77568978479/pkg/export/export.go#L804). This makes it more clear and accurate.
> use more accurate self-metrics

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- examples/frontend.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
This fixes the main configurations as well as a few examples. One of the prominent examples I have not covered here is the node-exporter because that has a few issues and I am not familiar with the exporter enough to determine if it would break anything. To be more specific, they have issues with using the host network and volume mounts which I don't believe we could remove.
> GKE Security Posture configuration fixes

- cmd/config-reloader/main.go
- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- examples/prometheus.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
We occasionally see spikes in [`reloader_reload_fails_total`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/vendor/github.com/thanos-io/thanos/pkg/reloader/reloader.go#L157) at startup due to the config-reloader hitting Prometheus's `/-/reload` endpoint before it's ready.
This change waits and polls for 2 minutes before timing out and exiting.
I tried to to do this with [K8s lifecycle `PostStart` hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks), specifically the `httpGet` action, but this didn't work because the container is killed if the hook fails. As the Prometheus server presumably takes some non-determinate amount of time to start, the hook would almost always fail and kill the container.
> If either a PostStart or …
> wait until Prometheus is ready before reloading

- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- cmd/operator/deploy/rule-evaluator/02-service-account.yaml
- cmd/operator/deploy/rule-evaluator/03-role.yaml
- cmd/operator/deploy/rule-evaluator/04-rolebinding.yaml
- manifests/rule-evaluator.yaml
When we [removed](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/0c2fcf209332a542e4af5326c413d2eb179f0984) the init container's root permissions, we also removed its ability to touch a file in `/etc/config/config.yaml`. This fixes that, and also makes it consistent with the managed-collection's [rule-evaluator](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/bcabe942c4bf2826a728f2d72baeafad437609ed/cmd/operator/deploy/operator/11-rule-evaluator.yaml#L41-L47).
Let's also add a rule-evaluator role and service account to allow k8s service discovery of alertmanagers, as was originally proposed in #367.
> Fix rule-evaluator init container

- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- manifests/operator.yaml
- pkg/export/export.go
- pkg/export/setup/setup.go
Update the user agent formatting to insert an environment `env` which is informed by checking the GCE metadata server [attributes](https://cloud.google.com/compute/docs/metadata/default-metadata-values#vm_instance_metadata).
> format user agent

- pkg/ui/ui.go
Preventing an infinite redirect loop. 
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/357.
See https://pkg.go.dev/net/http#example-ServeMux.Handle
> Only redirect at the root url

- cmd/operator/deploy/operator/12-alertmanager.yaml
- manifests/operator.yaml
In rare cases, the alertmanager pod can end up on a IP that is not a part of [RFC 6890](https://www.rfc-editor.org/rfc/rfc6890.html), which can cause error messages like:
```
ts=2022-12-10T13:01:12.632Z caller=main.go:263 level=error msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"
```
The [recommended fix](https://github.com/prometheus/alertmanager/blob/99a464c914ce265e9db2d64036c9785eb09f6a5e/README.md#high-availability) is to specify the `--cluster.advertise-address` flag. However, if the `--cluster.listen-address` is specified, [it is used](https://github.com/GoogleCloudPlatform/alertmanager/blob/v0.24.0-gmp.0/cluster/cluster.go#L175-L188) as the default.
This also mimics …
> fix issue with non-RFC 6890

- pkg/operator/operator.go
- pkg/operator/target_status.go
- pkg/operator/target_status_test.go
Discovered as part of #395
In the future, we could look into running lint checks on changed files, otherwise this fixes a few of those issues.
> Clean up target status related lint issues and improve error messages

- examples/rabbitmq/pod-monitoring.yaml
There are two common ways to install RabbitMQ which result in pods with different label selectors. Acknowledge both options in the example.
This manifest is embedded in https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/rabbitmq#exporter-podmonitoring which also includes a paragraph reminder to check this against the labels on the RabbitMQ pods.
> Update the RabbitMQ sample PodMonitoring manifest

- pkg/export/transform.go
To save on memory allocation, we reuse the cached distribution objects and clear out the values. This was never added for exemplars, so we were running into an issue where we would have exemplars from different series show up in others. This should fix that.
> Clear exemplars on distribution reset

- examples/prometheus.yaml
Since the `config-reloader` logic was [changed](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/edba0b43a3c502fb670a78e2adf0343e8abffd53) to return an error if there was a connection issue with the `ready-url`, the pod is never able to start.
`prometheus` is looking for the [config file output](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/c50410e403ce13bfd248f5d0d950988e858797f2/examples/prometheus.yaml#L100) from the `config-reloader` before returning a 200 on `/-/ready`, but since the `config-reloader` is exiting before its main routine, the file is never generated. So it's stuck in a broken loop.
The init container priming the pod with a [blank config](https://github.com/GoogleCloudPlatform/prometheus-engine/pull/422/commits/0487f2343ad9064b50ffa7c61ccf5 …
> add init container to prom example

- cmd/frontend/main.go
This makes authentication for the UI in the browser when `AUTH_USERNAME` and `AUTH_PASSWORD` are set. Otherwise, the UI is unprotected but errors because it cannot access `/api`.
> Extract auth function and add auth to UI

- pkg/operator/e2e/main_test.go
- pkg/operator/operator_config.go
Since the managed Alertmanager service is known, we can rely on [K8s DNS resolution](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services) of services to configure a static target to route alerts to.
This is an expected improvement over relying on K8s SD as it reduces the watch load in OOTB deployments.
> Use static target for managed Alertmanager

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
While extremely rare, we have seen cases where memory of these components can bleed up to the limits specified here.
> use higher limits for operator and rule-evaluator

- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- manifests/rule-evaluator.yaml
Increase evaluator memory limit to 1G
reset config-reloader to 32M from 1G
> Adjust rule-evaluator memory limits

- examples/kube-state-metrics/kube-state-metrics.yaml
Remove TODO given that 1.24 is now the default version in stable (https://cloud.google.com/kubernetes-engine/docs/release-notes-stable)
Testing plan: apply this manifest in a cluster, get no errors.
> Update sample KSM HPA API version

- .github/workflows/auto-assign.yml
Automatically assigns the team on a rotation basis. An internal script updates the repository's secret with the value of the week's user: https://github.com/GoogleCloudPlatform/prometheus-engine/settings/secrets/actions
> Add auto-assign to issues and PRs

- cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
- cmd/operator/deploy/crds/monitoring.googleapis.com_podmonitorings.yaml
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/types.go
Fix #491
Also adding validation for the field, based on the [regex provided in the Prometheus duration spec](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file).
> Set default interval for ScrapeEndpoint

- Makefile
- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- examples/prometheus.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
To prepare for the 0.7.1 release.
After this, we will update the release-0.7 branch by cherry-picking everything from 0.7.1 including this commit.
> Bump images to 0.7.1

- pkg/export/setup/setup.go
I previously removed the auto-populated default in GCE in https://github.com/GoogleCloudPlatform/prometheus-engine/commit/f2a1b010e37b7bf48b5f300e18f33df0d41e7277#diff-5b0aad29927670f209bb47d27f555506630c61d4c7c1c3fa8130bd99e9d5fe2aR97, causing the `cluster` label to not be auto-populated in GCE/GKE in ingested metrics to GMP.
This is the fix.
> fix cluster label auto-populate in GCE

- Makefile
- pkg/export/export.go
PR #481 missed a case where an external application was running unit tests.
> Fix tag detection on external unit tests

- pkg/operator/operator.go
- Leverage the client.IgnoreNotFound function to improve readability of some error handling.
- Wrap errors from controller-runtime.
> Refactor cleanup of old resources

- Makefile
- examples/frontend.yaml
This will ensure our manifests are auto-updated during `presubmit`
> add updateversions to presubmit

- pkg/export/export.go
- pkg/export/export_test.go
- pkg/export/setup/setup.go
- pkg/export/shard.go
This is useful to perform e2e benchmarks to fine tune more. It also allows advanced configuration for customers in unique environments.
> export: Exposed internal shard + buffer sizing flags as exorted options.

- hack/Dockerfile
Update from v0.11.1 to v0.20.1. This resolves a bug on my local development environment where kind cluster fails to create.
> Update kind used in kindtest target

- cmd/operator/deploy/operator/10-collector.yaml
- manifests/operator.yaml
All of the collector logs(INFO,DEBUG,etc) were showing up as ERRORs.
This's because GKE needs structured
logs(https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs#best_practices) to show log level correctly.
By using the JSON logger error levels will be displayed correctly.
Confirmed working in
https://github.com/GoogleCloudPlatform/prometheus/pull/74
> Use JSON logger for the collector

- cmd/config-reloader/main.go
- cmd/frontend/main.go
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/rule-evaluator/main.go
- manifests/operator.yaml
- pkg/export/export_test.go
Similar to https://github.com/GoogleCloudPlatform/prometheus-engine/pull/517. JSON logs are needed for GKE to display logs correctly. 
The following components were modified to use the JSON logger:
1. alertmanager
2. rule-evaluator
3. config-reloader
4. frontend
Tested with @TheSpiritXIII and confirmed working in GKE.
Tested in a clean GKE cluster without GMP enabled using: 
```
DOCKER_PUSH=1 make operator
DOCKER_PUSH=1 make rule-evaluator
DOCKER_PUSH=1 make config-reloader
DOCKER_PUSH=1 make frontend
kubectl apply -f manifests/setup.yaml 
kubectl apply -f manifests/operator.yaml 
kubectl apply -n gmp-system -f examples/frontend.yaml 
// Verify log levels in each component are appearing correctly.
```
pkg/export/export_test.go was updated to match the logger used in the collector that was …
> Use JSON logger for GMP components

- examples/mongodb/exporter.yaml
**Changes**
* [Updated the example for the MongoDB exporter to use new flag](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/4c5c85d3cab65f863b6b14d8b022792de33801c0)
**Details**
Based on this [PR](https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/pull/592), a newer version of the MongoDB exporter requires a flag for collecting metrics.
> Updated MongoDB exporter example to use new flag

- pkg/operator/rules.go
- pkg/operator/rules_test.go
Currently there is no syntax validation for GlobalRules and this causes customers to apply rule files with syntax errors. 
Syntax validation happen in [rules.Scope.](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/3016092cbcfec6181adb274e06aa5ea06503a500/pkg/rules/rules.go#L85) which is called by [GenerateRules and GenerateClusterRules.](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/3016092cbcfec6181adb274e06aa5ea06503a500/pkg/operator/rules.go#L213-L241)
This commit contains:
1. added `rules.Scope` to `GenerateGlobalRules`
2. Added unit test cases for `GenerateRules`, `GenerateClusterRules` and `GenerateGlobalRules`.
> Add syntax validation for GlobalRules

- examples/kube-state-metrics/kube-state-metrics.yaml
v2.8.2 is what our managed equivalent is currently using. This version bump resolves #547 because newer KSM invokes v1/CronJob API endpoints instead of v1beta1/CronJob endpoints, which have been deprecated since v1.21+ and unavailable in v1.25+. See https://github.com/kubernetes/kube-state-metrics/blob/main/CHANGELOG.md#v241--2022-02-10 for more context.
This switch breaks compatibility with K8s <v1.21, but this is not a concern given earliest version in GKE stable release channel is v1.23 and default is currently v1.27.
> Bump recommended KSM version

- cmd/config-reloader/Dockerfile
- cmd/frontend/Dockerfile
- cmd/operator/Dockerfile
- cmd/rule-evaluator/Dockerfile
- hack/Dockerfile
Need to update to golang:1.20.7 to fix security vulnerabilities.
golang 1.20-buster supports only until golang 1.20.5, it's also the oldoldstable of debian.
golang 1.20-bookworm is the current stable release. https://wiki.debian.org/DebianReleases
> Update Debian to latest stable release

- cmd/config-reloader/Dockerfile
- cmd/frontend/Dockerfile
- cmd/operator/Dockerfile
- cmd/rule-evaluator/Dockerfile
- examples/instrumentation/go-synthetic/Dockerfile
- hack/Dockerfile
Debian 12 is not supported yet.
Change `gcr.io/distroless/static:latest` to `gcr.io/distroless/static-debian11:latest` for consistency with GoogleCloudPlatform/prometheus and GoogleCloudPlatform/alertmanager
> use Debian 12

- pkg/export/export.go
Currently [grpc_client_handling_seconds](https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/a5446fa2489078304671617eeebd4c5e457dcf07/client_metrics.go#L80-L83) uses [`prom.DefBuckets`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/b07c5f3b326f793f8e411862a2b7e40961cb69f9/vendor/github.com/prometheus/client_golang/prometheus/histogram.go#L261-L265) which has a maximum bucket of 10. We need to add more granularity for our SLO. I added `15, 20, 30, 40, 50, 60`. I will adjust based on usage.
Tested and confirmed working.
> add more buckets to grpc_client_handling_seconds

- examples/instrumentation/go-synthetic/Dockerfile
- examples/instrumentation/go-synthetic/README.md
- examples/instrumentation/go-synthetic/auth.go
- examples/instrumentation/go-synthetic/main.go
Example usage:
```
go run ./examples/instrumentation/go-synthetic/ --basic-auth-username=admin --basic-auth-password=pw
curl localhost:8080/metrics -u "admin:pw"
```
> Add BasicAuth support into the example app

- examples/instrumentation/go-synthetic/README.md
- examples/instrumentation/go-synthetic/auth.go
- examples/instrumentation/go-synthetic/main.go
Example with bearer token:
```bash
go run ./examples/instrumentation/go-synthetic/ --auth-scheme=Bearer --auth-parameters=xyz
curl -H "Authorization: Bearer xyz" localhost:8080/metrics
```
This PR builds on top of #567.
> Add Authorization header support into the example app

- examples/instrumentation/go-synthetic/README.md
- examples/instrumentation/go-synthetic/auth.go
- examples/instrumentation/go-synthetic/main.go
Example usage:
```bash
go run ./examples/instrumentation/go-synthetic/ --oauth2-client-id=abc --oauth2-client-secret=xyz
curl "localhost:8080/token?grant_type=client_credentials&client_id=abc&client_secret=xyz"
curl -H "Authorization: Bearer DZ~9UYwD" localhost:8080/metrics
```
This PR builds on top of #568.
> Add OAuth 2.0 support into the example app

- Makefile
- README.md
- hack/kind-test.sh
Provides a uniform way of running a single test via our Makefile, no matter what other environment variables are used.
> Add ability to run individual tests

- examples/postgresql/exporter.yaml.snippet
* [updated yaml snippet based on new exporter release](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/a6a02e34b284b297b77900a8219549fb745d0b60)
Version `0.14.0` of the postgresql exporter has been released. There was an issue resolved regarding certain collectors not starting when the PostgreSQL database was not started completely. Also, there's a new flag/argument to include in the deployment to collect certain metrics.
> PostgreSQL Exporter: Update YAML snippet

- e2e/operator_context_test.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/ui/ui.go
This is effectively a no-op. The ioutils package today simply call the os packages. This removes some warnings in the codebase.
> Replace deprecated ioutil module usage

- examples/kube-state-metrics/kube-state-metrics.yaml
To support sample dashboard content:
`replicaset`  - [Kubernetes Infrastructure Promtheus Overview
](https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/blob/master/dashboards/kubernetes/k8s-overview-prometheus.json)
`job_created` - [Kubernetes Pod Prometheus Overview
](https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/blob/master/dashboards/kubernetes/k8s-pod-prometheus.json)
> add replicaset and specific job metric to support sample dashboards

- examples/instrumentation/go-synthetic/README.md
- examples/instrumentation/go-synthetic/auth.go
- examples/instrumentation/go-synthetic/main.go
- go.mod
Example usage:
```bash
go run ./examples/instrumentation/go-synthetic/ --tls-create-self-signed=true
curl -k https://localhost:8080/metrics
```
This PR builds on top of #569.
> Add mTLS support into the example app

- e2e/alertmanager_test.go
- e2e/collector_test.go
- e2e/operator_context_test.go
- e2e/ruler_test.go
- e2e/webhook_test.go
- go.mod
This PR is the first part of multiple for allowing tests to be able to run run isolated from each other. Currently some subtests are broken because they rely on configurations to get created from prior subtests.
Using labels for tests allows us to remove resources in subtests in the future to ensure that all subtests are completely independent. This also helps prevent name collisions in resources and allows tests to be more robust.  The existing tests already used labels for namespaces, but this expands them by making labels more explicit.
> Use subtest labels for cleanup

- pkg/operator/endpoint_status_builder.go
- pkg/operator/operator.go
- pkg/operator/operator_config.go
- pkg/operator/target_status.go
- pkg/operator/target_status_test.go
A few random linter error fixes.
> style: linter error fixes

- cmd/rule-evaluator/main.go
This code accomplishes three goals:
1. Remove grpc measurements since grpc is not used by the rule-evaluator.
2. Expose the export metrics collected by export.go. In the future, we may want to measure latencies of CreateTimeSeries.
3. Wrap Query requests sent to GCM API with an instrument RoundTripper to count return codes and measure latencies. This will give GMP more control over their SLO's and Alerts. 
This PR will resolve b/300157911
> Add HTTP middleware to rule-evaluator

- pkg/export/bench/README.md
- pkg/export/bench/app/example_app.go
- pkg/export/bench/run.sh
- pkg/export/bench/server.go
Fixes:
```
pkg/export/bench/server.go:33:6: main redeclared in this block
pkg/export/bench/example_app.go:143:6: other declaration of main
```
> Fix bench library error

- e2e/operator_context_test.go
- pkg/operator/collection_test.go
- pkg/operator/operator.go
- pkg/operator/target_status_test.go
Minor refactoring. Makes the code more readable because:
- The namespace in the type definition is used.
- The code is shorter and easier to write.
- You don't need multiple clientsets.
- You can change types you create effortlessly.
- We can create a special Kubernetes client which adds subtest labels automagically.
> Add support for generic Kubernetes client on e2e tests

- e2e/kubeclient.go
- e2e/operator_context_test.go
Builds on #580 and #577 to make integration tests easier to write.
> Automatically add subtest labels for cleanup on e2e tests

- e2e/operator_context_test.go
Webhooks are preventing e2e tests from running in parallel. This change makes the webhook server choose a random port per test.
Original description:
```
Disable the webhook server by default on e2e tests
This allows us to run e2e tests in parallel after #578 is merged. 🎉 
Disabling it is easier than assigning a new port per test.
```
> Allow e2e tests to run in parallel

- e2e/alertmanager_test.go
- e2e/collector_test.go
- e2e/operator_context_test.go
- e2e/ruler_test.go
Part 2 of #577. This fixes the tests so that each test can be run isolated via #573.
New tests fail if they are not independent, since resources are now cleaned up between subtests.
> Cleanup resources between subtests and make subtests isolated

- go.mod
- go.sum
- vendor/github.com/prometheus/common/config/http_config.go
- vendor/github.com/prometheus/common/expfmt/decode.go
- vendor/github.com/prometheus/common/expfmt/text_parse.go
- vendor/github.com/prometheus/common/model/value.go
- vendor/github.com/prometheus/common/model/value_float.go
- vendor/github.com/prometheus/common/model/value_histogram.go
- vendor/github.com/prometheus/common/model/value_type.go
- vendor/modules.txt
Something we missed when updating Prometheus to 2.41. As far as I know, there are no known consequences of not having already done this. I only discovered this because I wanted to add support for HTTP client authentication in a separate change and I was getting some marshalling errors without this.
> Update prometheus common library to match prometheus client library

- cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
- cmd/operator/deploy/crds/monitoring.googleapis.com_operatorconfigs.yaml
- cmd/operator/deploy/crds/monitoring.googleapis.com_podmonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/http.go
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/apis/monitoring/v1/types_test.go
- pkg/operator/operator_config.go
Adds min and max TLS version settings to match what Prometheus offers: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config
These were not there originally largely due to our Prometheus at the time (2.35) not offering them.
> Update TLS config to match Prometheus settings

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/main.go
- manifests/operator.yaml
- pkg/operator/operator.go
Currently, the GMP Operator accepts a Certificate for the webhook server
and a CA Cert for clients as arguments on the command line. This is not
the most secure way of passing the server certificate, as noted by
GKE Security (b/297043491#comment2).
This change allows these certificates to be passed as files instead of
command line arguments and prioritizes the files over the command line
args (args will be ignored if files exist).
Expected usage is that a Kubernetes Secret (`webhook-cert`) will be created with the server cert and
a ConfigMap (`webhook-ca`) will be created with the Client CA, which can then be
mounted to the operator as a projected volume at the default path of
`/etc/tls/private/`, using standard filenames `tls.crt`, `tls.key`, and
`ca.crt`, respectively.
The paths can be …
> Add ability to pass cert files to operator

- .github/dependabot.yaml
In https://github.com/GoogleCloudPlatform/prometheus-engine/pull/589, I added a dependabot config that just looks at the root directory. This just explicitly lists the directories we want to look at.
Let me know if we want to include '/hack' or not.
> Add explicit directories for updates

- cmd/operator/deploy/operator/03-role.yaml
- manifests/operator.yaml
The ability to delete the rule-evaluator deployment is no longer necessary.
> Remove delete permission for rule-evaluator deployment

- cmd/operator/deploy/operator/03-role.yaml
- manifests/operator.yaml
The ability to delete the collector DaemonSet is no longer necessary.
> Remove permissions to delete collector daemonset

- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- e2e/operator_context_test.go
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
Our current e2e tests are not deploying the Prometheus collector pods correctly on GitHub Actions due to 2 reasons:
1. GitHub Actions does not support "localhost". It only supports the loopback address directory.
2. GitHub Actions does not have Google Cloud credentials.
These issues cause the collector pods to crash loop indefinitely in e2e tests. cc @pintohutch
> Allow Prometheus to run GitHub Actions in e2e tests

- vendor/golang.org/x/net/internal/socks/socks.go
Something went off - build fails and it's not clear what's exactly not regenerated (https://github.com/GoogleCloudPlatform/prometheus-engine/actions/runs/6458765809/job/17533143057?pr=612), but the `make regen` indicates this vendor code. 
Sounds like dependanbot messed up. 🤔
> Run make regen.

- .github/dependabot.yaml
This is also due to potential issues with vendor file not being updated properly (investigating) https://github.com/GoogleCloudPlatform/prometheus-engine/pull/616
> Update dependabot.yaml to group PRs for gomod changes.

- e2e/alertmanager_test.go
- e2e/collector_test.go
- e2e/operator_context_test.go
- e2e/ruler_test.go
- hack/kind-test.sh
Provides the ability to leak and cleanup resources for an improved debugging experience, especially when running tests locally.
> Add options to leak and cleanup resources

- e2e/operator_context_test.go
Makes e2e cleanup faster by skipping deletion of any namespaced items. Namespaced items are deleted when the namespace is deleted.
> Faster e2e cleanup code

- e2e/network.go
- e2e/podutils.go
Fixes the issue where checking the target status refuses to work if an unrelated container (i.e. config-reloader) fails to start but the collector is fine.
> Make e2e network client more resilient to errors

- doc/api.md
- e2e/collector_test.go
- e2e/kubeutil/deployment.go
- e2e/kubeutil/parse.go
- e2e/kubeutil/pod.go
- e2e/network.go
- e2e/operator_context_test.go
- e2e/podmonitoringutil.go
- e2e/syntheticutil.go
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/collection.go
- pkg/operator/operator.go
- pkg/operator/target_status.go
Additionally this change:
- Creates generic utilities for checking if a PodMonitoring is started. This will be used in future PRs.
- Add labels to collectors so that self-scraping tests don't start looking at collectors outside of the current test.
> Add and parallelize target-status ClusterPodMonitoring e2e tests

- examples/nvidia-dcgm/exporter.yaml
PodMonitoring Selector looks for the label `app.kubernetes.io/name: nvidia-dcgm-exporter`
> Fix labels used by NVIDIA DCGM

- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/main.go
- manifests/operator.yaml
- pkg/operator/operator.go
Reverts GoogleCloudPlatform/prometheus-engine#601
This change broke self-installed with the error "init admission
resources: create cert file: open /etc/tls/private/tls.crt: read-only
file system"
> Revert "Add ability to pass cert files to operator"

- examples/instrumentation/go-synthetic/auth.go
Fixes allowing:
```bash
go run ./examples/instrumentation/go-synthetic/ --auth-scheme=Bearer 
curl -H "Authorization: Bearer" localhost:8080/metrics
curl -H "Authorization: Bearer " localhost:8080/metrics
```
> Support empty auth parameters in go-synthetic

- examples/hpa/prometheus-adapter.yaml
- hack/presubmit.sh
Replace deprecated generate-groups.sh script with recommended kube_codegen.sh script.
> chore: switch to kube-codegen

- Makefile
- examples/hpa/prometheus-adapter.yaml
Ensure only valid install manifests have their version updated, avoiding example manifests.
> fix: updateversions make target

- Makefile
- cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
- cmd/operator/deploy/crds/monitoring.googleapis.com_podmonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/export/export.go
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/apis/monitoring/v1/types_test.go
- pkg/operator/apis/monitoring/v1/zz_generated.deepcopy.go
Only pods that are not "Failed" or "Succeeded" will be default candidates for scraping.
BREAKING CHANGE: this changes the default behavior of PodMonitoring and ClusterPodMonitoring
> feat: pod lifecycle filtering

- pkg/operator/collection.go
- pkg/operator/operator.go
- pkg/operator/operator_config.go
The recent controller-runtime allows use to use a single cache for the operator and remove our hacky secondary cache.
> Use a single manager cache for the operator

- Makefile
- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/deploy/operator/05-deployment.yaml
- cmd/operator/deploy/operator/10-collector.yaml
- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- cmd/operator/deploy/operator/12-alertmanager.yaml
- cmd/operator/deploy/rule-evaluator/01-deployment.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
also bump the version and images
Note: I had to add the get/list/watch abilities to the ClusterRole instead of the Role. This is obviously less preferable, however the controller-runtime library errors if I add those to the role:
```
E1204 22:39:49.710415       1 reflector.go:140] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:gmp-system:operator" cannot list resource "statefulsets" in API group "apps" at the cluster scope
```
> fix operator role for alertmanager externalURL

- pkg/operator/operator.go
Webhook permissions check was underspecified. Operator only has permission to update specific webhookconfig, not all webhookconfigs.
Fix oversight on #661.
> fix: webhook permissons check

- e2e/authorization_test.go
- e2e/collector_test.go
- e2e/operator_context_test.go
- e2e/ruler_test.go
This PR adds a 3rd namespace to e2e tests.
Here's when you use each now:
1. `namespace`: The operator namespace. Use only for operator resources or for `PodMonitoring` or `ClusterPodMonitorings` that are self-scraping.
2. `pubNamespace`: The operator public namespace. Use only for resources that are stored here, e.g. `OperatorConfig` and the rule evaluator `ConfigMaps` and `Secrets` .
3. `userNamespace`: For everything else -- applications, `PodMonitorings` or `ClusterPodMonitorings`, application `Secrets`. etc.
> Add user namespace to e2e tests

- pkg/operator/operator.go
- pkg/operator/operator_test.go
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/696
I build `gcr.io/gpe-test-1/operator:bw-test5` from this branch and manually tested with self-deployed operator from manifests/.*
This essentially reverts https://github.com/GoogleCloudPlatform/prometheus-engine/pull/661, but I think it makes sense to revert, the case we tried to handle better was never seen (?), nor it's particularly harmful (periodic error log for a good reason is not too bad idea) 🤔
> operator: Fixed operator caBundle injection.

- .github/workflows/presubmit.yml
- Makefile
- e2e/alertmanager_test.go
- e2e/authorization_test.go
- e2e/collector_test.go
- e2e/kubeutil/container.go
- e2e/kubeutil/daemonset.go
- e2e/kubeutil/deployment.go
- e2e/kubeutil/pod.go
- e2e/operator_context_test.go
- e2e/operatorutil/collection.go
- e2e/operatorutil/podmonitoringutil.go
- e2e/ruler_test.go
- e2e/webhook_test.go
- hack/kind-test.sh
- Increases timeouts for a few tests.
- Ensures we don't poll too regularly and accidentally overload the Kubernetes API server.
- Ensures that we can recover when we get an error due to the Kubernetes API server being overloaded (e.g. try to fetch an object and get a timeout).
- Waits until collectors are up before validating the PodMonitoring status.
- Increases e2e timeout on GitHub Actions.
Why: I am adding more tests and without this change, the tests are very flaky.
> Improve e2e test reliability when running on GitHub Actions

- pkg/export/export.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
Context: This release branch is blocked by https://github.com/GoogleCloudPlatform/prometheus-engine/issues/696. This PR is meant to cherry pick #712 which fixed this in the main branch. See more context about the fix in the #712
Signed-off-by: bwplotka <bwplotka@google.com>
> Cherry-picked webhook fix #712 for upcoming 0.9.1-rc.1

- cmd/datasource-syncer/README.md
- cmd/datasource-syncer/main.go
- cmd/datasource-syncer/main_test.go
These changes ensure:
The **Timeout** field of the **HTTP** pane, set the value to 120.
The **Query timeout** field, set the value to 2m.
Also adding instructions for Workload identity.
> Add syncing timeouts and instructions for Workload identity

- cmd/operator/deploy/crds/monitoring.googleapis.com_nodemonitorings.yaml
- cmd/operator/deploy/operator/03-role.yaml
- cmd/operator/deploy/operator/08-validatingwebhookconfiguration.yaml
- doc/api.md
- examples/cadvisor-metrics.yaml
- examples/kubelet-metrics.yaml
- manifests/operator.yaml
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/register.go
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/collection.go
- pkg/operator/operator.go
Add the frontend part of NodeMonitoring and make port optional.
Tested via running the following commands:
1. `DOCKER_PUSH=1 make operator` 
2. `kubectl apply -f manifests/setup.yaml`
3. `kubectl apply -f manifests/operator.yaml`
4. `kubectl apply -f examples/cadvisor-metrics.yaml` and `kubectl apply -f examples/kubelet-metrics.yaml` 
You can see the node metrics being scraped after that. Additionally I toggled KubeletScraping on/off to watch the scraping turn off/on.
> feat: [kubelet/cAdvisor metrics package] add frontend for NodeMonitoring

- cmd/operator/deploy/crds/monitoring.googleapis.com_nodemonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/types.go
- pkg/operator/apis/monitoring/v1/types_test.go
Remove NodeMonitoring port.
It seems Kubelet just has [one port](https://pkg.go.dev/k8s.io/api/core/v1#NodeDaemonEndpoints) that is used by [Prometheus as the default](https://github.com/GoogleCloudPlatform/prometheus/blob/release-2.41.0-gmp/discovery/kubernetes/node.go#L196).
I suggest we remove port support to simplify our code until we have a good reason to add it.
@bwplotka @pintohutch do you see any reason to keep NodeMonitoring port?
> Remove NodeMonitoring port

- cmd/config-reloader/Dockerfile
- cmd/operator/Dockerfile
- cmd/rule-evaluator/Dockerfile
- hack/Dockerfile
I decided to break out the kind E2E test refactor PR https://github.com/GoogleCloudPlatform/prometheus-engine/pull/738 into smaller, digestible PRs for reviewing.
Note: because of the nature of the change, presubmits (i.e. Github Actions) may fail until the final PR is merged.
This is the first one, where we slim down our Docker images to only copy code that's necessary to build and run the binary or script.
> [E2E refactor - 1] slim down Dockerfiles

- cmd/operator/deploy/operator/03-role.yaml
- manifests/operator.yaml
- pkg/operator/rules.go
- pkg/operator/rules_test.go
Scale the Alertmanager StatefulSet and Rule Evaluator Deployment to zero when there are no active rules in the cluster.
> feat: autoscale alertmanager and rule-evaluator

- cmd/datasource-syncer/datasource-syncer.yaml
- cmd/datasource-syncer/main.go
- go.mod
1. Added TLS support, including four new flags `tls-cert`, `tls-key`, `tls-ca-cert` and `insecure-skip-verify`.
2. Added a condition to return error and exist if any data source syncs fail.
3. Added a label to datasource-syncer.yaml so users can use `kubectl get pods -l app=datasource-syncer` to view pods associated with their job.
> Add TLS to datasource-syncer

- .github/workflows/presubmit.yml
- .golangci.yml
- cmd/config-reloader/main.go
- cmd/datasource-syncer/main.go
- cmd/frontend/main.go
- cmd/operator/main.go
- cmd/rule-evaluator/main.go
- pkg/export/bench/app/example_app.go
- pkg/export/bench/server.go
- pkg/export/export.go
- pkg/export/export_test.go
- pkg/export/gcm/promtest/local_export.go
- pkg/export/gcm/promtest/promtest.go
- pkg/export/gcm/promtest/skip.go
- pkg/export/series_cache.go
- pkg/export/series_cache_test.go
- pkg/export/transform.go
- pkg/export/transform_test.go
- pkg/lease/lease.go
- pkg/operator/apis/monitoring/v1alpha1/types.go
- pkg/operator/collection.go
- pkg/operator/collection_test.go
- pkg/operator/operator.go
- pkg/operator/operator_config.go
- pkg/operator/rules.go
- pkg/operator/rules_test.go
- pkg/operator/target_status.go
- pkg/operator/target_status_test.go
- pkg/rules/rules_test.go
- pkg/ui/ui.go
Consolidated fixes after running linters on operator package.
Summary:
- Unused arguments changed to `_`
- `k8s.io/utils/pointer` is deprecated. Replace with `k8s.io/utils/ptr`.
- error messages start with lowercase letter.
- Exported functions have comments
- Packages are only imported once (including aliases).
- "if block ends with a return statement, so drop else and outdent its block"
Resolved or ignored (by line) linter errors and enabled default linters for golangci-lint, plus gofmt linter.
Enabled `make lint` in CI.
> style: resolve linter errors and enable linter

- pkg/operator/collection.go
NodeMonitorings will be generated by GMP using the operator namespace. Only apply them if KubeletScraping is disabled.
> fix: use operator namespace to check if a NodeMonitoring should be applied

- pkg/operator/endpoint_status_builder.go
- pkg/operator/target_status.go
- pkg/operator/target_status_test.go
After NodeMonitoring was added, when it is configured, target status stops working completely. Long story short, the problem is early exit on an unknown scrape pool format.
This change includes some refactoring originally part of the ProbeMonitoring PR (#766) but also adds in the possibility of supporting a NodeMonitoring target status if we choose to add it in the future, by at the very least detecting and validating the scrape pool format.
Changes include:
- Ensures we still patch everything on error (with new unit test case).
- Show all errors, not just the last one we found.
- Ensures we parse NodeMonitoring scrape pool formats (with new unit test case).
- Validate expected errors in the test cases.
Thanks @bwplotka for finding this issue!
> Fix NodeMonitoring breaks target status

- examples/self-pod-monitoring.yaml
This PR aims to reduce aim to reduct the amount of self-scraped metrics that are ingested.  
1. Increase the scrape interval to 30s.
2. Drop metrics with high cardinality.
Also resolves b/322791992 and part of https://github.com/GoogleCloudPlatform/prometheus-engine/issues/725
> fix: update self-pod-monitoring.yaml example to reduce ingestion of self-scraped metrics.

- .github/workflows/presubmit.yml
- Makefile
Using `go run` instead of running the binary inside of Docker reduces the linting time considerably, from on the order of a minute with Docker to about 3-5 seconds using `go run`.
> ci: change make lint command

- pkg/export/export.go
This is for consistency.
Related (priv): cl/599259750 and b/315381075
> export: Fixed error metric ("no-ha-range" -> "not-in-ha-range").

- .github/workflows/presubmit.yml
I decided to break out the kind E2E test refactor PR https://github.com/GoogleCloudPlatform/prometheus-engine/pull/738 into smaller, digestible PRs for reviewing.
Note: because of the nature of the change, presubmits (i.e. Github Actions) may fail until the final PR is merged.
This is the ninth one, where we use parallel Github Actions to run each kind cluster test in parallel for faster and more reliable tests (< 10m total).
> [E2E refactor - 9] use matrix strategy to parallelize github action e2e test runs

- Makefile
- hack/kind-test.sh
I decided to break out the kind E2E test refactor PR https://github.com/GoogleCloudPlatform/prometheus-engine/pull/738 into smaller, digestible PRs for reviewing.
Note: because of the nature of the change, presubmits (i.e. Github Actions) may fail until the final PR is merged.
This is the eleventh (and really final!) one, where we fix a bug that allows a build and deploy of the go-synthetic container from source. Also reduce the parallelism for local e2e test runs to improve stability.
> [E2E refactor - 11] fix go-synthetic e2e deploy and reduce local parallelism

- cmd/operator/deploy/operator/11-rule-evaluator.yaml
- manifests/operator.yaml
This was missed in #690, and needs to be fixed for autoscaling the rule-evaluator to work correctly on GKE.
> fix: remove replica count for rule-evaluator

- hack/kind-test.sh
Due to https://github.com/kubernetes-sigs/kind/issues/623, we need to
ensure we do not violate the length of a kind cluster's name.
We have been ensuring unique cluster names by using the name of the go
test function as the cluster name. However, for longer functions, we run
into this issue.
This change fixes the length of the name to 32 characters and appends a
random hash to the end of the name to prevent collisions for
similarly-named tests.
> Limit size of kind cluster names

- .github/workflows/presubmit.yml
- hack/kind-test.sh
This fixes two issues:
1. `TEST_RUN` takes in a regular expression. After the recent refactoring, this no longer works. This is because we create a kind cluster with a name based off of the TEST_RUN. If there any special characters (e.g. from regular expressions), this fails.
2. If we add a new text that's a prefix or suffix of the same test, that test will be ran twice on GitHub. For example, if we have `TestA` and `TestAVariant`, then when GitHub runs `TestA`, it will run both tests within that runner and then it will run `TestAVariant` again in a separate runner. This is because Go takes in a regular expression when filtering tests and `TestA` matches both tests. We fix this by adding symbols for start and end of string, e.g. we run `TestA` with `^TestA$` to ensure it only runs …
> fix: match exact test on e2e test matrix

- .github/dependabot.yaml
Basically, dependabot tries to be smart. It detects the previous commit message, and then extrapolates based on that to determine how to to create the next one.
With `include: scope` on, we should not include the scope in the prefix, because [it will be included again](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L110).
> chore: fix dependabot commit scopes

- .golangci.yml
- cmd/rule-evaluator/main.go
- pkg/export/export.go
- pkg/export/pool_test.go
- pkg/export/series_cache.go
- pkg/export/transform.go
- pkg/export/transform_test.go
- pkg/operator/operator_test.go
misspell: `Finds commonly misspelled English words.`
> style: enable misspell linter

- .golangci.yml
- pkg/export/transform_test.go
predeclared: `Find code that shadows one of Go's predeclared identifiers.`
> chore: enable predeclared linter

- .golangci.yml
- pkg/operator/target_status_test.go
nilerr: `Finds the code that returns nil even if it checks that the error is not nil.`
> chore: enable nilerr linter

- .golangci.yml
- cmd/rule-evaluator/main.go
- pkg/export/gce_token_source.go
usestdlibvars: A linter that detect the possibility to use variables/constants from the Go standard library.
> style: enable usestdlibvars linter

- .github/workflows/release-please.yml
This is expected to resolve the issue where the release-please PR is being created by the GitHub Actions bot, which is not approved for the CLA.
> chore: use gmp-bot token for release-please

- .conform.yaml
Add `main` as allowed commit message scope for Conform rules.
> chore: add main to allowed commit scopes

- .github/workflows/auto-assign-pr-schedule.yml
Upload-artifact@v3 uses deprecated Node.js 16.
> chore: update to upload-artifact@v4

- .github/workflows/release-please.yml
In addition to releasing from `main`, release on release branches.
> chore: release from release branches

- .release-please-manifest.json
- pkg/export/export.go
Automatically bump the version in `export.go` with release-please.
> chore: automate export.go version bump

- charts/rule-evaluator/Chart.yaml
- charts/rule-evaluator/templates/_helpers.tpl
- charts/rule-evaluator/templates/configmaps.yaml
- charts/rule-evaluator/templates/deployment.yaml
- charts/rule-evaluator/templates/role.yaml
- charts/rule-evaluator/templates/rolebinding.yaml
- charts/rule-evaluator/templates/service-account.yaml
- charts/rule-evaluator/values.yaml
- hack/presubmit.sh
See comparison: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.10.0-rc.2/manifests/rule-evaluator.yaml
- Added indentation to templates [as per best practices](https://helm.sh/docs/chart_best_practices/templates/#formatting-templates).
- Added standard labels to all resources [as per best practices](https://helm.sh/docs/chart_best_practices/labels/#standard-labels).
- Added a flag `noCommonLabels` which disables standard labels. Setting this flags to `true` gives you our original labels.
- Fixed our deployment pod now correctly uses the `AppVersion` variable.
- We're now using the previously-defined `serviceAccount` variables.
- Added a `rbac` variable [as per best practices](https://helm.sh/docs/chart_best_practices/rbac/#yaml-configuration).
- Fixed consistency around …
> refactor: cleanup rule-evaluator Helm chart

- charts/operator/Chart.yaml
- charts/operator/templates/_helpers.tpl
- charts/operator/templates/alertmanager.yaml
- charts/operator/templates/collector.yaml
- charts/operator/templates/deployment.yaml
- charts/operator/templates/mutatingwebhookconfiguration.yaml
- charts/operator/templates/namespace.yaml
- charts/operator/templates/priority-class.yaml
- charts/operator/templates/role.yaml
- charts/operator/templates/rolebinding.yaml
- charts/operator/templates/rule-evaluator.yaml
- charts/operator/templates/service-account.yaml
- charts/operator/templates/service.yaml
- charts/operator/templates/validatingwebhookconfiguration.yaml
- charts/operator/values.yaml
- hack/presubmit.sh
- manifests/operator.yaml
Updated labels to match 1:1 to our last 0.10.0 version.
See comparison: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.10.0-rc.2/manifests/operator.yaml
The concern is that users will start to depend on these new labels (e.g. scaling), which would make it difficult to remove them in the future.
- Added indentation to templates [as per best practices](https://helm.sh/docs/chart_best_practices/templates/#formatting-templates).
- Added standard labels to all resources [as per best practices](https://helm.sh/docs/chart_best_practices/labels/#standard-labels).
- Added a flag `noCommonLabels` which disables standard labels. Setting this flags to `true` gives you our original labels.
- Fixed our deployment pod now correctly uses the `AppVersion` variable.
- We're now using the …
> refactor: cleanup operator Helm chart

- charts/operator/crds/monitoring.googleapis.com_operatorconfigs.yaml
- doc/api.md
- examples/export-write/README.md
- examples/export-write/prometheus-receiver.yaml
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/operator_types.go
- pkg/operator/collection.go
This is an example of how GMP collectors can be configured to send metrics to a central Prometheus receiver.
1. Added a URL flag to OperatorConfig, this flag is then used to set `remote_write` in the Prometheus config.
2. examples/export-write contains the manifest to launch a central Prometheus that accepts incoming write requests.
> feat: export write from collectors to central prometheus example

- cmd/config-reloader/main.go
This bug was introduced in https://github.com/GoogleCloudPlatform/prometheus-engine/pull/788
The issue is we always try to close the response body, but the response body is `nil` if there is an error (e.g. service is unavailable). 
`defer` is also incorrect because `defer` executes when the surrounding function returns. Because this method runs in a loop, it will keep gathering more and more responses to close. As such, I just close the body all the time now since we never even use the body.
Discovered while testing https://github.com/GoogleCloudPlatform/prometheus-engine/pull/892
> fix: fix config reloader panics if the response is nil

- .golangci.yml
- e2e/deploy/operator.go
Always import "k8s.io/apimachinery/pkg/api/errors" as apierrors.
> style: enforce apierrors alias

- cmd/config-reloader/Dockerfile
- cmd/datasource-syncer/Dockerfile
- cmd/frontend/Dockerfile
- cmd/operator/Dockerfile
- cmd/rule-evaluator/Dockerfile
- examples/instrumentation/go-synthetic/Dockerfile
Enable boringcrypto flag for Go builds.
Cherry-picked https://github.com/GoogleCloudPlatform/prometheus-engine/commit/748b809569fccb5e556c1870b7870d0ff843fe5d
> chore: enable boringcrypto

- charts/operator/templates/rule-evaluator.yaml
- charts/rule-evaluator/templates/deployment.yaml
- cmd/config-reloader/main.go
- go.mod
- go.sum
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
- vendor/github.com/thanos-io/thanos/pkg/errutil/multierror.go
- vendor/github.com/thanos-io/thanos/pkg/reloader/reloader.go
- vendor/github.com/thanos-io/thanos/pkg/runutil/runutil.go
- vendor/modules.txt
This feature upgrades Thanos to support config directories.
~~This will be kept as a draft until the next Thanos release.~~
Update: Due to popular demand, we can release this before the next Thanos release. It should be okay since my patch should have been the only reloader change.
Depends on https://github.com/GoogleCloudPlatform/prometheus-engine/pull/895
> feat: support decompressing config directories in config-reloader

- .release-please-manifest.json
- release-please-config.json
This should cause release-please to read the manifest file that specifies it should update the version in `export.go`.
> chore: reference release-please manifest

- cmd/config-reloader/Dockerfile
- cmd/config-reloader/boring.go
- cmd/operator/Dockerfile
- cmd/operator/boring.go
- cmd/rule-evaluator/Dockerfile
- cmd/rule-evaluator/boring.go
cgo needs to be enabled to link against boringcrypto, so we add that here.
In addition, we use the google-go.pkg.dev/golang image as the Go buildbase to ensure build-time requirements, like boringcrypto, are enabled.
We also use gke.gcr.io/gke-distroless/libc as our runtime image.
We add the "cryp/tls/fipsonly" import to ensure boringcrypto is linking properly at build time. We guard this with a build tag "boring" in a dedicated file.
> chore: enable cgo and use google buildbase

- pkg/operator/apis/monitoring/v1/common_types.go
- pkg/operator/apis/monitoring/v1/node_types.go
- pkg/operator/apis/monitoring/v1/node_types_test.go
- pkg/operator/apis/monitoring/v1/pod_types.go
- pkg/operator/apis/monitoring/v1/pod_types_test.go
Related to https://github.com/GoogleCloudPlatform/prometheus-engine/issues/479
Without this, certainly malformed CR could trigger Prometheus config parsing error, distrupting the whole cluster collection config changes.
Also to provide better fix to potentially #479 (vs creating separate CR) we could add e.g. JobNameSuffix field for endpoint, but that's for another PR.
> fix(operator): add duplicate job name validation within PM, CPM and CNM

- pkg/secrets/kubernetes.go
- pkg/secrets/kubernetes_test.go
- pkg/secrets/watch.go
The configuration reload fails if the caller (the Prometheus collector) does not have permission to view the secret. This change allows the configuration reload to pass, and retries the secret watch until the caller gives permission. A new unit test was added to support this change.
> fix: retry watch forbidden secrets

- examples/instrumentation/go-synthetic/go-synthetic-basic-auth.yaml
(rebased on top of @TheSpiritXIII branch)
> feat(examples): add go-synthetic (example-app) example for basic auth with new GMP secret feature

- charts/operator/templates/deployment.yaml
- cmd/operator/main.go
- e2e/deploy/operator.go
- e2e/webhook_test.go
- manifests/operator.yaml
- pkg/operator/operator.go
This PR improves the reliability of the operator.
This is useful for moving the operator to the control plane (if we ever do), for customers to avoid the 0-node problem themselves, and for us to simplify our e2e test logic (makes our guitar test more reliant too).
> Add healthz and readyz to operator

- pkg/operator/operator.go
Only load the scaling controller when VPA is enabled in the cluster.
> fix: configurable vpa

- examples/cadvisor-metrics.yaml
- examples/kubelet-metrics.yaml
Added a comment to remind maintainers to update the public documentation whenever changes are made to the metric collection configuration. This will help ensure that the documentation remains accurate and up-to-date.
> chore: reminder to update cAdvisor docs

- cmd/datasource-syncer/datasource-syncer.yaml
The GCP [Configure and authenticate the Grafana data source](https://cloud.google.com/stackdriver/docs/managed-prometheus/query#grafana-oauth) documentation instructs users to apply this `datasource-syncer.yaml` to deploy datasource syncer to their Kubernetes cluster.
However, there is a default taint `kubernetes.io/arch=arm64:NoSchedule` on every ARM node launched from GKE clusters, preventing the syncer jobs from being scheduled.
I referred to the linked `grafana.yaml` below from this repository to add affinity configurations, allowing the jobs to be scheduled on ARM nodes. I tested it in my GKE cluster and it works.
https://github.com/GoogleCloudPlatform/prometheus-engine/blob/2ca623dfb091dbec98344bf98ab43c917b7cdfe4/examples/grafana.yaml#L29-L42
> fix: allow datasource-syncer to run on arm64 nodes

- charts/datasource-syncer/templates/cronjob.yaml
- charts/datasource-syncer/templates/job.yaml
- cmd/datasource-syncer/datasource-syncer.yaml
Change https://github.com/GoogleCloudPlatform/prometheus-engine/pull/960 was missing the helm change.
> fix: helm chart to run datasource-syncer to run on arm64 nodes

- charts/operator/templates/alertmanager.yaml
- charts/operator/templates/collector.yaml
- charts/operator/templates/deployment.yaml
- charts/operator/templates/rule-evaluator.yaml
- charts/rule-evaluator/templates/deployment.yaml
- cmd/operator/main.go
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
- pkg/operator/operator.go
See internal go/k8s-security-validation-service-user-guide
Two changes:
- The `readOnlyRootFilesystem` flag prevents an attacker from overriding the binary. For the GMP operator, I moved the certificate creation into an empty directory to avoid writing into the root filesystem.
- We were missing `seccompProfile` for rule-evaluator, but we have it everywhere else.
Other warnings are more involved (such as trimming update RBAC permissions).
> fix: cleanup security validation warnings

- Makefile
- pkg/operator/operator.go
[GCR is being phased out](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr). This change allows us to push dev images, like those created with `DOCKER_PUSH=1 make operator`, to Artifact Repository instead of Container Registry.
> chore: switch dev images to AR instead of GCR

- .conform.yaml
- cmd/rule-evaluator/main.go
- pkg/export/export.go
- pkg/export/export_test.go
- pkg/export/gcm/promtest/local_export.go
- pkg/export/setup/setup.go
The way our e2e tests are written is usually we check for the GMP collector to start-up correctly.
The problem is that if we defer the metadata labeling to the configuration as opposed to flags, then the collector will never start-up correctly (and also goes against our goal which is to prevent the collector from restarting at initialization).
The simple solution here is to defer error handling until we have a configuration with scape or rule configurations.
See also: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/965
> feat(export): allow GMP collectors to startup without metadata

- e2e/alertmanager_test.go
- e2e/authorization_test.go
- e2e/collector_test.go
- e2e/kube/daemonset.go
- e2e/kube/debug.go
- e2e/kube/deployment.go
- e2e/ruler_test.go
- e2e/webhook_test.go
Show debug Prometheus collector logs when an e2e test fails to startup.
I was running into an issue that only happened on GitHub Actions. How this works:
1. Use a context that times out right before the test. This ensures the test catches the timeout and can "cleanup" or in this case, show logs before exiting.
2. Show debug logs in the test. We use a new context in case the test timed out, and the original context cannot be reused.
> test(e2e): debug pod logs

- charts/operator/templates/collector.yaml
- charts/values.global.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
Wanted clean state here and what I can import into latest manifest release.
> feat: update manifests with new prom image and delete flag

- cmd/config-reloader/Dockerfile
- cmd/operator/Dockerfile
- cmd/rule-evaluator/Dockerfile
This fixes an issue with images on ARM64.
Tested and verified fix on ARM64 and AMD64 machines.
Testing steps:
```
docker buildx build --builder mybuilder -t gcr.io/$PROJECT_ID/prometheus-engine/operator:arm-test1 cmd/operator/Dockerfile --platform linux/arm64,linux/amd64 --build-arg QEMU_VERSION=latest --push
docker buildx build --builder mybuilder -t gcr.io/$PROJECT_ID/prometheus-engine/config-reloader:arm-test1 cmd/operator/Dockerfile --platform linux/arm64,linux/amd64 --build-arg QEMU_VERSION=latest --push
docker buildx build --builder mybuilder -t gcr.io/$PROJECT_ID/prometheus-engine/rule-evaluator:arm-test1 cmd/operator/Dockerfile --platform linux/arm64,linux/amd64 --build-arg QEMU_VERSION=latest --push
kubectl apply -f manifests/operator.yaml
```
> fix: Use upstream go image for build

- pkg/export/setup/setup.go
This reverts an accidental change in https://github.com/GoogleCloudPlatform/prometheus-engine/pull/514
> fix: Use default shard count in export

- e2e/deploy/operator.go
- e2e/kube/debug.go
- e2e/kube/pod.go
- e2e/ruler_test.go
Sometimes e2e tests fail if a deployment pod fails to startup, and restarts, or the GMP operator causes the pod to restart and we query the pod too quick.
The quick and easy fix is to only filter active pods.
> fix(e2e): reduce e2e flakiness when a deployment pod restarts

- .github/workflows/presubmit.yml
[setup-go@v5](https://github.com/actions/setup-go?tab=readme-ov-file#v5) updates to Node 20 from Node 16, which is [deprecated as of September 11, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol).
> chore: update setup-go action

- pkg/operator/collection.go
- pkg/operator/collection_test.go
Made sure monitoring statuses are propagated when there is a failure.
Added a test case for it. Test logic wasn't modified. Only added variables to be able to change the podmonitoring and error messages.
> fix: ensure status is added to crds

- e2e/authorization_test.go
- pkg/operator/apis/monitoring/v1/http_types.go
- pkg/operator/apis/monitoring/v1/http_types_test.go
Fixes the issue shared through https://github.com/GoogleCloudPlatform/prometheus-engine/pull/776#issuecomment-2087606662.
The current implementation only supports a PodMonitoring selecting a Secret from the `default` namespace.
The existing E2E test cases were using a Secret deployed inside the `default` namespace therefore not covering this "edge" case:
https://github.com/GoogleCloudPlatform/prometheus-engine/blob/f21c2ba4c0a9c3108209c1e59ec75d52e388235e/e2e/authorization_test.go#L96-L177
> fix(operator): support secrets outside default ns for scrape auth

- examples/nvidia-dcgm/pod-monitoring.yaml
NVIDIA dcgm-exporter captures and records the "pod", "namespace", and "container" labels. We should honor those in our relabeling.
Hence, we use a ClusterPodMonitoring with an empty .targetLabels.metadata (akin to what we do for KSM) to preserve them.
> fix: use clusterpodmonitoring for nvidia-dcgm

- pkg/operator/apis/monitoring/v1/http_types_test.go
Adds test case for scenario fixed by https://github.com/GoogleCloudPlatform/prometheus-engine/pull/995
This test fails in the 0.13 release branch but passes on main now that the above PR has been merged.
> test: add defaulting edge case for secret key selector

- examples/nvidia-dcgm/exporter.yaml
Context: b/345755257
Verified via https://kubernetes.io/docs/concepts/storage/volumes/?spm=a2c63.p38356.0.0.28874dcbfWkCRx#hostpath-volume-types this is a well-defined option.
> Update DCGM sample YAML so that /home/kubernetes/bin/nvidia is not created if it does not exist

- examples/nvidia-dcgm/exporter.yaml
Same as #1009 but for the DCGM daemonset -- missed that there were two identical definitions (one for DCGM, one for DCGM exporter).
> docs: update dcgm daemonset sample yaml

- Makefile
- charts/operator/Chart.yaml
- cmd/config-reloader/Dockerfile
- cmd/datasource-syncer/Dockerfile
- cmd/frontend/Dockerfile
- cmd/rule-evaluator/Dockerfile
- examples/instrumentation/go-synthetic/Dockerfile
- hack/Dockerfile
- manifests/operator.yaml
- pkg/export/export.go
* This specifically fixes CVE-2024-24790 in the config-reloader and frontend containers.
* We also update all Dockerfiles to use 1.22-bullseye.
* We ensure we specify the image sha for precesion and repeatability.
* We prepare the manifests to tag v0.11.2.
> fix(deps): bump golang to 1.22-bullseye

- charts/operator/crds/monitoring.googleapis.com_clusternodemonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/node_types.go
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/807
And ensures we have full feature parity with the original Kubelet scraping options.
> feat: add insecure-skip-verify field to ClusterNodeMonitoring scrape endpoint

- pkg/operator/apis/monitoring/v1/pod_types.go
- pkg/operator/collection.go
- pkg/operator/collection_test.go
If webhooks are not running for some unknown reason, we will want to default objects.
> feat: default CRDs on the reconcile loop

- cmd/datasource-syncer/Dockerfile
- cmd/frontend/Dockerfile
- examples/instrumentation/go-synthetic/Dockerfile
Matches what we have in the release/0.12 branch. However, the release/0.12 branch forgot to update go-synthetic.
> chore: update to Go 1.22.4 for non-critical cmds

- charts/operator/templates/role.yaml
- manifests/operator.yaml
- pkg/operator/rules.go
- pkg/operator/rules_test.go
This PR helps us get rid of our Deployment and StatefulSet RBAC policies one day (in favor of only allowing the scale sub-resource).
> refactor: use scale subresource to update replica counts

- charts/operator/templates/collector.yaml
- manifests/operator.yaml
Reverts https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1027 (the flag part) to reduce the backporting risk. This flag (which fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/459) will be added in 0.13.
> revert(configs): revert 0.12.0 --gmp.storage.delete-data-on-start flag

- charts/operator/templates/mutatingwebhookconfiguration.yaml
- charts/operator/templates/role.yaml
- charts/values.global.yaml
- e2e/collector_test.go
- e2e/ruler_test.go
- examples/collector-max-throughput.yaml
- manifests/operator.yaml
- pkg/operator/collection.go
- pkg/operator/labels.go
- pkg/operator/labels_test.go
- pkg/operator/operator_config.go
- pkg/operator/operator_config_test.go
- pkg/operator/rules.go
- pkg/operator/webhook.go
Pass GKE metadata through the Prometheus configuration rather than using flags.
See original attempt: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/920
Prerequisites:
1. prometheus-engine: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/977
2. prometheus: https://github.com/GoogleCloudPlatform/prometheus/pull/162
> refactor: prevent collector pod restarts on startup

- cmd/rule-evaluator/README.md
- cmd/rule-evaluator/main.go
- pkg/export/export.go
- pkg/export/export_test.go
- pkg/export/gcm/promtest/local_export.go
- pkg/export/setup/setup.go
- pkg/export/setup/setup_test.go
This PR cleans up all export flags so that:
- The code is more readable as it's more broken up by function.
- We could move these options to YAML one day and update them at runtime instead of at startup.
Changes:
- Ensures all flag values have their own struct.
- Move flag validation and defaulting to their own methods.
- Ensure all flag structs have only serializable values (e.g. `ExporterOpts.Lease` was moved out).
- Use URLs with `kingpin` (flag library) to avoid needing to parse strings manually.
I also broke up the monstrosity that was the `setup` package exporter constructor which returned a function that would create an exporter. The reason this was done was because first we setup flags and then returned a method that would create the exporter once the flags were parsed. Now you …
> refactor: cleanup export flags

- cmd/rule-evaluator/README.md
- cmd/rule-evaluator/main.go
Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1001 (this helps me reuse the projectID flag from the --export.project_id flag).
See b/350551533 for details.
> feat: include Google Cloud links for alerts

- hack/kind-test.sh
Current sed regex breaks if there's no tag. We're moving to tag-less images, so this fixes that problem.
> test: support kind tests with images without tags

- charts/datasource-syncer/templates/cronjob.yaml
- cmd/datasource-syncer/README.md
- cmd/datasource-syncer/datasource-syncer.yaml
fix: change data source syncer period to 10 minutes
Every 30 minutes meant that there could be at most 1 network timeout before losing connection. Running every 10 minutes instead makes it much less likely that a networking hiccup will cause Grafana to fail.
> fix: change data source syncer period to 10 minutes

- charts/operator/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
- charts/operator/crds/monitoring.googleapis.com_podmonitorings.yaml
- doc/api.md
- manifests/setup.yaml
- pkg/operator/apis/monitoring/v1/pod_config.go
- pkg/operator/apis/monitoring/v1/pod_config_test.go
- pkg/operator/apis/monitoring/v1/pod_types.go
- pkg/operator/collection_test.go
Implement go/gmp:expand-target-labels.
> feat: workload labels

- pkg/operator/operator.go
Using the cleanup flag today causes the operator to crash-looping because we don't include the DELETE RBAC permission by default.
This happened because we used to do all resource creation/update/deletion on the operator but we moved it to YAML. This also makes the cleanup function consistent, as we warn when we can't delete everything else.
> fix: show warning when cleaning up old resources without delete permissions

- pkg/operator/endpoint_status_builder.go
- pkg/operator/target_status_test.go
We had not tested ClusterNodeMonitoring-generated cadvisor scrape targets, which have an additional path suffix in the scrape pool. We consider that here when building the endpoint status and add a unit test.
This fixes #1097.
> fix: Support target status for cadvisor

- examples/cadvisor-metrics.yaml
- examples/kubelet-metrics.yaml
Cherry-pick f30fa3ab7956eafd8f7c5f248baf381030e5fdab from `main` onto the `release/0.13 branch`, as this is what we're deploying in the 0.13 release candidates.
> fix: cadvisor/kubelet example regex

- charts/operator/templates/alertmanager.yaml
- manifests/operator.yaml
Set automountServiceAccountToken: false for alertmanager StatefulSet.
The pods of this daemonset don't interact with the kubernetes API. Security best practices recommend that we either use a dedicated service account for this pod or set automountServiceAccountToken: false.
> Do not automount initcontainer service account token

- charts/values.global.yaml
- cmd/datasource-syncer/datasource-syncer.yaml
- examples/frontend.yaml
- examples/instrumentation/go-synthetic/go-synthetic-basic-auth.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
First, we preemptively tag the binaries in this repo with their anticipated Docker image tags from the build pipeline.
Secondly, we bump the tags of prometheus and alertmanager to match what we expect will be deployed in the final manifest.
> chore: prepare v0.13.1 release candidate

- charts/operator/values.yaml
- charts/rule-evaluator/values.yaml
- cmd/datasource-syncer/datasource-syncer.yaml
- examples/frontend.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
Our tagging pipeline was non-functional for a period, leading us to relying on using the image shas instead of tags.
Now that the pipeline is functional again, we can provide convenient image tags for reference and installations.
Fixes #1081
> chore: add image tags to manifests

- charts/rule-evaluator/values.yaml
- manifests/rule-evaluator.yaml
The standalone rule-evaluator image was incorrectly tagged in 353231bf3e90965e72c2ce77ab0f3367892ab2ac.
> fix: use correct rule-evalutor image in manifest

- examples/self-pod-monitoring.yaml
The gmp-operator exposes Prometheus metrics that can be helpful to debug issues with managed-collection. This is also the case with the managed alertmanager.
We have examples of how to scrape metrics from other components, but not the operator or the alertmanager.
So here we provide examples to supplement the self-monitoring exporter documented in
https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/prometheus?hl=en.
Partly addresses #793.
> feat: add more example self-podmonitorings

- charts/values.global.yaml
- e2e/collector_test.go
- manifests/operator.yaml
- pkg/operator/collection.go
~~Pre-req: https://github.com/GoogleCloudPlatform/prometheus/pull/179~~
Uses the new config settings instead of CLI flags for prometheus, and makes DaemonSet UPDATE permissions optional.
> feat: move Prometheus flags to config

- charts/values.global.yaml
- e2e/alertmanager_test.go
- go.mod
- manifests/operator.yaml
- pkg/operator/operator.go
- pkg/operator/operator_config.go
- vendor/github.com/prometheus/alertmanager/config/config.go
- vendor/github.com/prometheus/alertmanager/config/coordinator.go
- vendor/github.com/prometheus/alertmanager/config/notifiers.go
- vendor/github.com/prometheus/alertmanager/pkg/labels/matcher.go
- vendor/github.com/prometheus/alertmanager/pkg/labels/parse.go
- vendor/github.com/prometheus/alertmanager/timeinterval/timeinterval.go
- vendor/modules.txt
Uses the new config settings instead of CLI flags for alertmanager, and makes StatefulSet UPDATE permissions optional.
> feat: update alertmanager flags at runtime

- pkg/export/export.go
We previously only logged an error when this happened, which can be hard to debug. Particularly in cases where we are writing to more than one project.
This change introduces a counter `gcm_export_samples_sent_errors_total` that is incremented every time a send call to GCM returns an error. We add the `project_id` as a label to help better inform the destination project that is experiencing the issue.
On a given collector or rule-evaluator, the cardinality of `project_id` values should be relatively small, O(100) in the more extreme cases.
> feat: add samples sent error counter

- examples/prometheus.yaml
The tags used in our examples/prometheus.yaml were way out of date. This updates them to match those tagged in `v0.12.0-imgtag`.
Opened b/361070946 to track making this process automated as part of presubmit.
> fix: use latest image tags in prometheus example

- cmd/rule-evaluator/main.go
- pkg/operator/collection.go
- pkg/operator/operator_config.go
- pkg/operator/operator_config_test.go
~~Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1104~~
The following are now settable in the rule-evaluator Prometheus config:
```yaml
google_cloud:
query:
project_id: []string
generator_url: string
credentials: string
```
When both CLI arguments and configurations are present, the CLI arguments will be the default and the set configurations will override the CLI arguments.
For now, this is only settable at startup time. https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1129 allows setting on runtime.
> feat: allow loading rule-evaluator query options from config

- e2e/collector_test.go
- e2e/ruler_test.go
- pkg/operator/operator_config.go
Pre-req: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1129
Uses the new config settings instead of CLI flags for rule-evaluator, and makes Deployment UPDATE permissions optional.
> feat: set rule-evaluator options using config

- charts/values.global.yaml
- cmd/datasource-syncer/datasource-syncer.yaml
- examples/instrumentation/go-synthetic/go-synthetic-basic-auth.yaml
- examples/instrumentation/go-synthetic/go-synthetic.yaml
- examples/prometheus.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
We prepare the image manifests to refer to the published images stored in GKE GCR before tagging.
> chore: prepare v0.13.0 release

- pkg/operator/operator_config.go
Remove `setContainerExtraArgs` helper as it is unused and causing lint failures
> chore: remove unused helper

- cmd/datasource-syncer/main.go
It's requested by a customer who wants to pass the Grafana API token as an environment variable when deploy the datasource-syncer on Cloud Run.
The environment variable could have the API token as plain text or get the value from the GCP's Secret Manager service.
> feat: allow environment variable for GMP Grafana datasource-syncer

- e2e/kube/pod.go
- pkg/lease/lease.go
- pkg/operator/operator.go
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which, compared to the default JSON encoding, reduces CPU consumption related to (de)serialization, reduces overall latency of the API calls, reduces memory footprint and the work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
Core system components of K8s default their serialization method to protobuf for 8 years already: https://github.com/kubernetes/kubernetes/pull/25738.
Some benchmarks comparing JSON vs. protobuf showcasing how the latter data format (de)serializes faster and uses less memory:
- https://medium.com/@akresling/go-benchmark-json-v-protobuf-4ec3c62ec8d4
- https://www.codingexplorations.com/blog/performance-comparison-protobuf-marshaling-v …
> Use protobuf encoding for core K8s APIs in Prometheus Engine

- charts/values.global.yaml
- cmd/datasource-syncer/datasource-syncer.yaml
- examples/frontend.yaml
- examples/instrumentation/go-synthetic/go-synthetic-basic-auth.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
Cherry pick of https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1117/files#diff-812b265e1da8d8a3c64370d7d4b87bd6d109bda0d44b066ee86b8329d4004f43 and distroless bump.
> chore: update manifests to 0.13.1

- .conform.yaml
- cmd/frontend/Dockerfile
Rationale: https://github.com/GoogleCloudPlatform/prometheus-engine/actions/runs/10990949209/job/30521085208?pr=1149
403 on launcher.gcr.io/google/nodejs means it's suddenly private for unknown reasons. Luckily there is an alternative registry documented on the (archived) repo https://github.com/GoogleCloudPlatform/nodejs-docker
Also added conform rules for missing components.
> fix(frontend): use the alternative registry for the same image

- cmd/rule-evaluator/internal/alerts.go
- cmd/rule-evaluator/internal/alerts_test.go
- cmd/rule-evaluator/internal/api.go
- cmd/rule-evaluator/internal/api_test.go
- cmd/rule-evaluator/internal/rules.go
- cmd/rule-evaluator/internal/rules_test.go
- cmd/rule-evaluator/main.go
Adding a prometheus-compatible API endpoint to rule-evaluator: /api/v1/alerts
> feat: add /api/v1/alerts endpoint

- .dockerignore
- charts/operator/templates/rule-evaluator.yaml
- charts/rule-evaluator/templates/service.yaml
- cmd/frontend/README.md
- cmd/frontend/internal/rule/client.go
- cmd/frontend/internal/rule/client_test.go
- cmd/frontend/internal/rule/proxy.go
- cmd/frontend/internal/rule/proxy_test.go
- cmd/frontend/main.go
- cmd/rule-evaluator/internal/api.go
- e2e/ruler_test.go
- hack/Dockerfile
- internal/promapi/promapi.go
- internal/promapi/promapi_test.go
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
Enabling to query `/api/v1/rules` and `/api/v1/alerts` from the `frontend` by proxying these calls to the `rule-evaluator` pod.
This PR also creates a k8s service manifest for the `rule-evaluator` in order to be able to reach it from `frontend`
Note:
~~There was no proper way to test the k8s manifests in an actual cluster. If there is a way to test this setup properly before merging, that would probably be advisable.~~
Update: Added e2e tests
> feat: add rules-evaluator proxy calls to frontend

- charts/values.global.yaml
- cmd/datasource-syncer/Dockerfile
- cmd/datasource-syncer/datasource-syncer.yaml
- examples/frontend.yaml
- examples/instrumentation/go-synthetic/go-synthetic-basic-auth.yaml
- examples/instrumentation/go-synthetic/go-synthetic.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
- pkg/export/export.go
(also bumped DS go version)
cherry-pick of 84b958e3c862488bdbaeb60bd5ef0a7b9c4688fb
> chore: prepare v0.14.0 release candidate

- cmd/frontend/README.md
- cmd/frontend/main.go
- cmd/rule-evaluator/README.md
- cmd/rule-evaluator/main.go
Adding a log level flags to both `rules-evaluator` & `frontend` binaries. The flag is named `--log.level`
> feat: add log level flag to rules-evaluator & frontend

- cmd/frontend/main.go
- cmd/rule-evaluator/Dockerfile
- cmd/rule-evaluator/main.go
- internal/promapi/buildinfo.go
- internal/promapi/buildinfo_test.go
- internal/promapi/promapi.go
This PR will make the GMP frontend compatible with Grafana for alerting and recording rules. It will also enable the rule-evaluator to be used as a datasource, albeit only for alerting and recording rules. 
Currently, Grafana won't attempt to import any rules without the `/api/v1/status/buildinfo` endpoint available. This PR adds it.
Adding the rule-evaluator as a Prometheus Datasource works as well with this feature. It produces an error when adding the datasource, due to it not implementing the `/api/v1/query` endpoint and its siblings. It does however succeed in importing the rules into Grafana. The GMP frontend will work without said error message.
The `/api/v1/status/buildinfo` endpoint is used by Grafana in order to determine the "flavor" of a Prometheus Datasource (Mimir / Cortex / …
> feat: add /api/v1/status/buildinfo endpoint for Grafana compatibility

- examples/instrumentation/go-synthetic/main.go
Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.
> update links to openmetrics to reference the v1.0.0 release

- pkg/operator/target_status.go
- pkg/operator/target_status_test.go
Clear EndPointStatuses when PodMonitoring does not have an endpoint.
This fixes a bug where PodMonitorings without any endpoints have a stale list of endpoints.
> fix: Clear EndpointStatuses for PodMonitoring without endpoints

- .github/workflows/automerge-dependabot.yml
Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request
Inspiration on client_golang: https://github.com/prometheus/client_golang/blob/main/.github/workflows/automerge-dependabot.yml
> chore: Add GH action for automerging dependabot PRs

- examples/nvidia-triton/README.md
- examples/nvidia-triton/pod-monitoring.yaml
- examples/tgi/README.md
- examples/tgi/pod-monitoring.yaml
- examples/vllm/README.md
- examples/vllm/pod-monitoring.yaml
These will be embedded in new docs at https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/introduction for how to instrument and observe these workloads.
> Add new sample manifests for GKE AI workloads

- cmd/config-reloader/Dockerfile
- cmd/datasource-syncer/Dockerfile
- cmd/frontend/Dockerfile
- cmd/operator/Dockerfile
- cmd/rule-evaluator/Dockerfile
- examples/instrumentation/go-synthetic/Dockerfile
- hack/Dockerfile
> 0.14: Cherry-pick image changes, given Louhi scripts were updated; upgraded to the latest Go 1.23.6

- .github/dependabot.yaml
- examples/scripts/go.mod
Use [directories instead of directory](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--) to simplify Dependabot configuration.
Add `release/0.16` branch to scanning list.
Scan `datasource-syncer` and `go-synthetic`.
> chore: simplify dependabot config

- .golangci.yml
- cmd/rule-evaluator/internal/alerts_test.go
- cmd/rule-evaluator/internal/api.go
Relates to: https://github.com/GoogleCloudPlatform/prometheus-engine/issues/1551
> test: expanded rules api/v1/alerts tests to avoid confusion

- .gitattributes
In theory this should help by minimizing diffs view for tagged files by default in the GitHub UI . See [the docs here](https://github.com/github-linguist/linguist/blob/main/docs/overrides.md)
The following files/directories are now marked as generated to reduce diffs:
- `vendor/**`
- `go.sum`
> feat: Add .gitattributes to minimize diffs

- .github/workflows/release-bot.yml
- Makefile
- hack/prepare_rc/cmd.go
- hack/prepare_rc/main.go
This PR introduces a new script `hack/prepare_rc` and workflow `release-bot.yml` that automates the process of preparing a release candidate. It does the following when passed in a new commit and branch from another workflow:
- Checks if the commit is a merge of a RC prep PR and if so tags it correctly
- Detects the new RC version by looking at the last rc tag and last release tag
- Note that a release tag of the format `vX.Y.Z` must be present before it bumps up the patch version, otherwise it will bump the RC version
- Updates the `mainModuleVersion` in `pkg/export/export.go` to the new version (should differ only if there has been a patch bump).
- Updates the `version` and image tags in `charts/values.global.yaml` to the new RC version.
- Runs `make regen` (ignoring `.github/` due to …
> feat: add workflow to prepare a release candidate

- .github/workflows/trigger-release-bot.yml
- Makefile
New workflow triggers `.github/workflows/release-bot.yml` from `main` in a centralized way. See #1664 for the PR this depends on.
> feat: auto-trigger RC PR creation on release/0.16 branch

- .github/workflows/release-bot.yml
The `github.repository_owner` expands to upper case letters when used, so we have to hardcode it
> fix: use lower case for image name

- .github/workflows/trigger-release-bot.yml
Give the release bot job a better name, used to test new PR automation
> chore: rename release-bot job

- .github/dependabot.yaml
- charts/values.global.yaml
- cmd/datasource-syncer/datasource-syncer.yaml
- manifests/operator.yaml
- manifests/rule-evaluator.yaml
Also adjusted dependabot as funnny enough, it nicely notified us about this
https://github.com/GoogleCloudPlatform/prometheus-engine/actions/runs/17222882290/job/48861825066?pr=1733
> chore: bump GMP version to the latest prod

- e2e/collector_test.go
- pkg/operator/collection.go
- pkg/operator/rules.go
Turns out the bug I was chasing in https://github.com/GoogleCloudPlatform/prometheus-engine/pull/1688#issuecomment-3233978114 when I extended test was unrelated to the PR -- we had this bug since [the move to dynamic config](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/43fff2a692f5b3573a2cc9580e0cd0ab5d5df9b3#r164799102)
Essentially we were propagating wrong compression option - config compression instead of the collection one.
Not a biggie as it's either none/gzip, but let's fix it! (:
> fix: operator propagate correct compression for collection

- examples/instrumentation/go-synthetic/README.md
- examples/instrumentation/go-synthetic/go-synthetic-utf8.yaml
- examples/instrumentation/go-synthetic/main.go
This is for easier testing for UTF-8 flows.
> feat: extend example go-synthetic for UTF-8 naming cases

- examples/configuration/target-filtering/README.md
- examples/configuration/target-filtering/pod-monitoring-allowlist.yaml
- examples/configuration/target-filtering/pod-monitoring-denylist.yaml
Allowlist is pretty scary (it's what cx usually do). For filtering deny listing is generally safer and easier, so wanted to ensure we have an example for that.
> chore: updated metricRelabeling example with denylist
